import assert from 'node:assert/strict';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('analise','Análise de Pace',async p=>{await p.getByRole('button',{name:/^Análises/}).click();await p.getByRole('button',{name:'Análise de Pace',exact:true}).click();});
const geometry=[];
const measure=(p,ref)=>p.evaluate(ref=>{const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Análise de Pace'&&e.getClientRects().length),head=title.closest('header'),summary=ref?head.parentElement.querySelector('section'):document.querySelector('.pace-summary');return Object.fromEntries(Object.entries({title,head,summary}).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,height:r.height}];}));},ref);
try{
for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){const p=await h.open(width),ref=await h.open(width,'',true);await p.locator('.pace-summary').waitFor();await h.capture(p,`app-${width}`);await h.capture(ref,`reference-${width}`);const row={width,app:await measure(p,false),reference:await measure(ref,true)};geometry.push(row);await h.write('geometry.json',geometry);for(const k of ['title','head','summary'])for(const d of ['x','y','width','height']){if(k==='title'&&d==='width')continue;assert.ok(Math.abs(row.app[k][d]-row.reference[k][d])<=1,`${width} ${k}.${d}: ${row.app[k][d]} / ${row.reference[k][d]}`);}await p.close();await ref.close();}
const fail=await h.open(1440,'&failOnce=pipelinePace');await fail.getByRole('alert').getByRole('button',{name:'Tentar novamente'}).click();await fail.locator('.pace-summary').waitFor();await fail.close();
const slow=await h.open(1440,'&slow=pipelinePace&failOnce=pipelinePace');await slow.getByRole('alert').waitFor();await slow.clock.pauseAt(new Date('2026-09-18T18:05:00Z'));await slow.getByRole('button',{name:'Tentar novamente'}).click();await slow.getByRole('status').filter({hasText:'Calculando análise'}).waitFor();await slow.clock.fastForward(2100);await slow.locator('.pace-summary').waitFor();await slow.close();
for(const[width,q]of [[390,''],[1024,''],[1440,'&theme=dark'],[1440,'&empty'],[1440,'&won'],[1440,'&super'],[1440,'&blocked']]){const p=await h.open(width,q);await p.locator('.pace-summary').waitFor();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.equal(await p.getByText(/NaN|Infinity/).count(),0);if(q.includes('super'))await p.getByText('super meta 133%',{exact:true}).waitFor();if(q.includes('won'))await p.getByText(/Tudo que a esteira render/).waitFor();if(q.includes('empty'))await p.getByText('Nenhum lead nas etapas comerciais do produto ativo.').waitFor();if(q.includes('blocked'))await p.getByText(/O desdobramento parou em taxa de fechamento/).waitFor();await h.capture(p,`state-${width}-${q||'responsive'}`);if(!q.includes('won')){await p.getByText('Ritmo diário e origem das taxas',{exact:true}).click();await p.getByText('Contato',{exact:true}).waitFor();await h.capture(p,`rates-${width}-${q||'responsive'}`);}await p.close();}
assert.deepEqual(h.errors,[]);console.log('Pace: geometria, dados completos, meta/super meta, taxas insuficientes, vazio, carga/erro/retry, mobile e escuro OK.');
}finally{await h.close();}
