import assert from 'node:assert/strict';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('calls','Análise de Pitches',async p=>{await p.getByRole('button',{name:/^Análises/}).click();await p.getByRole('button',{name:'Análise de Pitches',exact:true}).click();});
const geometry=[];
const measure=(p,ref)=>p.evaluate(ref=>{const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Análise de Pitches'&&e.getClientRects().length),head=title.closest('header'),filter=ref?head.parentElement.querySelectorAll('section')[0]:document.querySelector('.calls-filters'),temp=ref?head.parentElement.querySelectorAll('section')[1]:document.querySelector('.call-distribution');return Object.fromEntries(Object.entries({title,head,filter,temp}).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,height:r.height}]}));},ref);
try{
for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){const p=await h.open(width),ref=await h.open(width,'',true);await p.locator('.call-distribution').waitFor();await h.capture(p,`app-${width}`);await h.capture(ref,`reference-${width}`);const row={width,app:await measure(p,false),reference:await measure(ref,true)};geometry.push(row);await h.write('geometry.json',geometry);for(const k of ['title','head','filter','temp'])for(const d of ['x','y','width','height']){if(k==='title'&&d==='width')continue;assert.ok(Math.abs(row.app[k][d]-row.reference[k][d])<=1,`${width} ${k}.${d}: ${row.app[k][d]} / ${row.reference[k][d]}`);}await p.close();await ref.close();}
const p=await h.open(1440);await p.getByRole('button',{name:/Rafael Moura 7/}).click();await p.waitForFunction(()=>window.__callsReads.at(-1).closer==='leo');await p.getByRole('button',{name:'Gerar diagnóstico',exact:true}).click();await p.getByText('Diagnóstico fictício de venda: leo.',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>window.__callsWrites[0].body.scriptKey),'call');assert.match(await p.getByRole('link',{name:'virar treino →'}).first().getAttribute('href'),/#training\?objecao=/);assert.equal(await p.getByRole('link',{name:/Abrir gravação/}).first().getAttribute('target'),'_blank');await p.getByRole('button',{name:'Qualificação · SDR',exact:true}).click();await p.getByRole('heading',{name:'Diagnóstico da qualificação (IA)'}).waitFor();assert.equal(await p.locator('.calls-ai-result').count(),0);await p.getByRole('button',{name:'Gerar diagnóstico',exact:true}).click();await p.getByText('Diagnóstico fictício de sdr: todos.',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>window.__callsWrites.at(-1).body.scriptKey),'novo');await p.locator('.call-recent-row>button').first().focus();await p.keyboard.press('Enter');await p.getByRole('dialog').waitFor();await h.capture(p,'lead-open');await p.close();
const fail=await h.open(1440,'&failOnce=pitchCalls');await fail.getByRole('alert').getByRole('button',{name:'Tentar novamente'}).click();await fail.locator('.call-distribution').waitFor();await fail.close();
const aiFail=await h.open(1440,'&failOnce=improvePitch');await aiFail.getByRole('button',{name:'Gerar diagnóstico',exact:true}).click();await aiFail.getByRole('alert').waitFor();await aiFail.getByRole('button',{name:'Tentar diagnóstico novamente'}).click();await aiFail.locator('.calls-ai-result').waitFor();await aiFail.close();
const slow=await h.open(1440,'&slow=improvePitch');await slow.locator('.call-distribution').waitFor();await slow.clock.pauseAt(new Date('2026-09-18T18:05:00Z'));await slow.getByRole('button',{name:'Gerar diagnóstico',exact:true}).click();assert.ok(await slow.getByRole('button',{name:'Analisando…',exact:true}).isDisabled());assert.ok(await slow.getByRole('button',{name:'Qualificação · SDR',exact:true}).isDisabled());await slow.clock.fastForward(2100);await slow.locator('.calls-ai-result').waitFor();assert.equal(await slow.evaluate(()=>window.__callsWrites.length),1);await slow.close();
const stale=await h.open(1440,'&slow=improvePitch');await stale.locator('.call-distribution').waitFor();await stale.clock.pauseAt(new Date('2026-09-18T18:05:00Z'));await stale.getByRole('button',{name:'Gerar diagnóstico',exact:true}).click();await stale.getByRole('button',{name:'Trocar de produto: LeverAds'}).click();await stale.getByRole('button',{name:'Elo',exact:true}).click();await stale.getByText('Nenhuma call de venda resumida ainda',{exact:true}).waitFor({state:'attached'});await stale.clock.fastForward(2100);await stale.getByText('Nenhuma call de venda resumida ainda',{exact:true}).waitFor();assert.equal(await stale.locator('.calls-ai-result').count(),0);assert.equal(await stale.evaluate(()=>window.__callsReads.at(-1).saas),'elo');await stale.close();
for(const[width,q]of [[390,''],[1024,''],[1440,'&theme=dark'],[1440,'&empty'],[1440,'&small'],[1440,'&noAi']]){const page=await h.open(width,q);if(!q.includes('empty'))await page.locator('.call-distribution').waitFor();else await page.getByText('Nenhuma call de venda resumida ainda',{exact:true}).waitFor();if(q.includes('small'))await page.locator('.call-analysis-warning').waitFor();if(q.includes('noAi'))assert.ok(await page.getByRole('button',{name:'Gerar diagnóstico',exact:true}).isDisabled());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await h.capture(page,`state-${width}-${q||'responsive'}`);await page.close();}
assert.deepEqual(h.errors,[]);console.log('Pitches: geometria, grupo/pessoa, diagnóstico/erro/retry, bloqueio de duplicação, abertura por teclado, gravação, treino, mobile e escuro OK.');
}finally{await h.close();}
