import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('creative','Canvas',async p=>{await p.getByRole('button',{name:/^Marketing/}).click();await p.getByRole('button',{name:'Canvas',exact:true}).click();},{nativeTimers:true});
const ready=async p=>{await p.locator('.canvas-preview canvas:visible').waitFor();await p.getByRole('button',{name:'Baixar PNG',exact:true}).waitFor();await p.waitForFunction(()=>!document.querySelector('.canvas-preview button')?.disabled && document.querySelector('.canvas-preview canvas')?.width===1080);await p.getByText('carregando fontes da marca…',{exact:true}).waitFor({state:'hidden'});};
async function measure(p,ref){return p.evaluate(ref=>{const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Canvas'&&e.getClientRects().length),head=title.closest('header'),grid=document.querySelector(ref?'.canvas-grid':'.canvas-workspace');return Object.fromEntries(Object.entries({title,head,gallery:grid.children[0],preview:grid.children[1],content:grid.children[2]}).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,height:r.height}]}));},ref);}
const geometry=[];
async function png(p,button,height){const pending=p.waitForEvent('download');await p.getByRole('button',{name:button,exact:true}).click();const dl=await pending,buf=await fs.readFile(await dl.path());assert.equal(buf.toString('hex',0,8),'89504e470d0a1a0a');assert.equal(buf.readUInt32BE(16),1080);assert.equal(buf.readUInt32BE(20),height);return dl.suggestedFilename();}
try {
 for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){const p=await h.open(width),ref=await h.open(width,'',true);await ready(p);await h.capture(p,`app-${width}`);await h.capture(ref,`reference-${width}`);const row={width,app:await measure(p,false),reference:await measure(ref,true)};geometry.push(row);await h.write('geometry.json',geometry);for(const k of ['title','head','gallery','preview','content'])for(const d of ['x','y','width','height']){if((k==='title'&&d==='width')||(['gallery','preview','content'].includes(k)&&d==='height'))continue;assert.ok(Math.abs(row.app[k][d]-row.reference[k][d])<=1,`${width} ${k}.${d}: ${row.app[k][d]} / ${row.reference[k][d]}`);}await p.close();await ref.close();}
 const p=await h.open(1440);await ready(p);assert.match(await png(p,'Baixar PNG',1920),/story-chamada/);const field=p.locator('.canvas-field textarea').first(),original=await field.inputValue();await field.fill('Teste de *criativo*');await p.getByLabel('Fonte de Título · slide 1',{exact:true}).fill('1');await field.focus();assert.equal(await p.getByLabel('Fonte de Título · slide 1',{exact:true}).inputValue(),'20');await p.getByRole('button',{name:'Adicionar texto',exact:true}).click();await p.getByLabel('Texto adicional',{exact:true}).fill('Texto de apoio');await p.getByRole('button',{name:'Adicionar botão',exact:true}).click();await p.getByLabel('Botão adicional',{exact:true}).fill('Saiba mais');await h.capture(p,'edited');p.once('dialog',d=>d.dismiss());await p.getByRole('button',{name:'Resetar',exact:true}).click();assert.equal(await field.inputValue(),'Teste de *criativo*');p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'Resetar',exact:true}).click();assert.equal(await field.inputValue(),original);assert.equal(await p.getByLabel('Texto adicional',{exact:true}).count(),0);
 await field.fill('Manter alteração');p.once('dialog',d=>d.dismiss());await p.getByRole('button',{name:/^Feed 1080/}).click();assert.equal(await field.inputValue(),'Manter alteração');p.once('dialog',d=>d.accept());await p.getByRole('button',{name:/^Feed 1080/}).click();await p.waitForFunction(()=>document.querySelector('.canvas-preview canvas').height===1350);await png(p,'Baixar PNG',1350);await p.getByRole('button',{name:/^Carrossel 1080/}).click();await p.getByRole('button',{name:'Slide 2',exact:true}).click();assert.equal(await p.locator('.canvas-preview canvas:visible').getAttribute('aria-label'),`${await p.locator('.canvas-template[aria-pressed=true] strong').innerText()} · slide 2`);assert.match(await png(p,'Baixar PNG',1350),/2de4/);
 await p.close();
 const carousel=await h.open(1440);await ready(carousel);await carousel.getByRole('button',{name:/^Carrossel 1080/}).click();const downloads=[];carousel.on('download',d=>downloads.push(d));await carousel.getByRole('button',{name:'Baixar todos',exact:true}).click();await h.capture(carousel,'carousel-export');await carousel.getByRole('button',{name:'Baixar PNG',exact:true}).waitFor();assert.equal(downloads.length,4);for(const d of downloads){const b=await fs.readFile(await d.path());assert.equal(b.readUInt32BE(16),1080);assert.equal(b.readUInt32BE(20),1350);}await carousel.close();
 const failure=await h.open(1440);await ready(failure);await failure.evaluate(()=>{window.originalToBlob=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(cb){cb(null)};});await failure.getByRole('button',{name:'Baixar PNG',exact:true}).click();await failure.getByRole('alert').filter({hasText:'gerar o PNG'}).waitFor();await failure.evaluate(()=>{HTMLCanvasElement.prototype.toBlob=window.originalToBlob;});await png(failure,'Baixar PNG',1920);await failure.close();
 const slow=await h.open(1440);await ready(slow);await slow.evaluate(()=>{window.originalToBlob=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(...args){window.releasePng=()=>window.originalToBlob.apply(this,args);};});await slow.getByRole('button',{name:'Baixar PNG',exact:true}).click();await slow.waitForFunction(()=>window.releasePng);assert.ok(await slow.locator('.canvas-field textarea').first().isDisabled());assert.ok(await slow.getByRole('button',{name:/^Feed 1080/}).isDisabled());assert.ok(await slow.getByRole('button',{name:'Resetar',exact:true}).isDisabled());const pending=slow.waitForEvent('download');await slow.evaluate(()=>window.releasePng());await pending;await slow.getByRole('button',{name:'Baixar PNG',exact:true}).waitFor();await slow.close();
 const photo=await h.open(1440);await ready(photo);await photo.locator('.canvas-template').filter({has:photo.getByText('Foto',{exact:true})}).click();const image=await photo.evaluate(()=>{const c=document.createElement('canvas');c.width=c.height=32;const ctx=c.getContext('2d');ctx.fillStyle='#efb14b';ctx.fillRect(0,0,32,32);return c.toDataURL().split(',')[1];});
 const chooser=photo.waitForEvent('filechooser');await photo.getByRole('button',{name:'Escolher foto',exact:true}).click();await(await chooser).setFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await photo.getByRole('button',{name:'Trocar foto',exact:true}).waitFor();await png(photo,'Baixar PNG',1920);await photo.getByRole('button',{name:'Remover foto',exact:true}).click();await photo.getByRole('button',{name:'Escolher foto',exact:true}).waitFor();await photo.close();
 for(const[width,q]of [[390,''],[1024,''],[1440,'&theme=dark'],[1440,'&marketing&product=elo']]){const page=await h.open(width,q);await ready(page);await h.capture(page,`state-${width}-${q||'responsive'}`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.getByRole('button',{name:'Adicionar botão',exact:true}).click();await page.getByLabel('Botão adicional',{exact:true}).fill('Ação no celular');await h.capture(page,`content-${width}-${q||'responsive'}`);await page.close();}
 assert.deepEqual(h.errors,[]);console.log('Canvas: edição, descarte, slides, fotos, PNG 1080×1920/1350, falha/retry, espera, mobile, escuro e marca Elo OK.');
}finally{await h.close();}
