import assert from 'node:assert/strict';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('desempenho','Análise de Desempenho',async p=>{await p.getByRole('button',{name:/^Análises/}).click();await p.getByRole('button',{name:'Análise de Desempenho',exact:true}).click();});
const geometry=[];
const measure=(p,ref)=>p.evaluate(ref=>{const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Análise de Desempenho'&&e.getClientRects().length),head=title.closest('header'),sdr=ref?head.parentElement.querySelector('section'):document.querySelector('.performance-sdr');return Object.fromEntries(Object.entries({title,head,sdr}).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,height:r.height}]}));},ref);
const ready=async p=>{await p.getByRole('button',{name:'Detalhes de Leonardo',exact:true}).waitFor();};
try{
for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){const p=await h.open(width),ref=await h.open(width,'',true);await ready(p);await h.capture(p,`app-${width}`);await h.capture(ref,`reference-${width}`);const row={width,app:await measure(p,false),reference:await measure(ref,true)};geometry.push(row);await h.write('geometry.json',geometry);for(const k of ['title','head','sdr'])for(const d of ['x','y','width','height']){if((k==='title'&&d==='width')||(k==='sdr'&&d==='height'))continue;assert.ok(Math.abs(row.app[k][d]-row.reference[k][d])<=1,`${width} ${k}.${d}: ${row.app[k][d]} / ${row.reference[k][d]}`);}await p.close();await ref.close();}
const p=await h.open(1440);await ready(p);await p.getByRole('button',{name:'Adicionar social selling de Leonardo',exact:true}).click();await p.getByText('Registro atualizado',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>window.__performanceWrites[0].body.day),'2026-09-18');await p.getByRole('button',{name:'Detalhes de Leonardo',exact:true}).focus();await p.keyboard.press('Enter');await p.locator('.performance-sdr').getByRole('button',{name:'Copiar relatório',exact:true}).click();assert.match(await p.evaluate(()=>navigator.clipboard.readText()),/Social selling: 7 feitos/);await p.locator('.performance-sdr').getByRole('button',{name:'Juliana Alves',exact:true}).click();await p.getByRole('dialog').waitFor();await p.getByRole('dialog').getByRole('button',{name:'Fechar lead',exact:true}).click();await p.getByRole('button',{name:'Detalhes de Lucas',exact:true}).click();await p.locator('.performance-closer').getByRole('button',{name:'Copiar relatório',exact:true}).click();assert.match(await p.evaluate(()=>navigator.clipboard.readText()),/Receita: R\$ 14\.400/);await p.getByRole('button',{name:'Semana',exact:true}).click();await p.waitForFunction(()=>window.__performanceReads.at(-1).win.since==='2026-09-14');await ready(p);assert.equal(await p.getByRole('button',{name:'Adicionar social selling de Leonardo',exact:true}).count(),0);assert.equal(await p.locator('.performance-detail').count(),0);await p.getByRole('button',{name:'Período anterior',exact:true}).click();await p.waitForFunction(()=>window.__performanceReads.at(-1).win.since==='2026-09-07');await p.getByRole('button',{name:'Mês',exact:true}).click();await p.waitForFunction(()=>window.__performanceReads.at(-1).win.since==='2026-09-01');await p.close();
for(const method of ['scoreboard','desempenho']){const fail=await h.open(1440,`&failOnce=${method}`);await fail.getByRole('alert').getByRole('button',{name:'Tentar novamente'}).click();await ready(fail);await fail.close();}
const fail=await h.open(1440,'&failOnce=desempenhoLog');await ready(fail);await fail.getByRole('button',{name:'Adicionar social selling de Leonardo',exact:true}).click();await fail.getByRole('alert').waitFor();assert.equal(await fail.evaluate(()=>window.__performanceWrites.length),0);await fail.getByRole('button',{name:'Adicionar social selling de Leonardo',exact:true}).click();await fail.getByText('Registro atualizado',{exact:true}).waitFor();await fail.close();
const accepted=await h.open(1440,'&writeReadFail');await ready(accepted);await accepted.getByRole('button',{name:'Adicionar social selling de Leonardo',exact:true}).click();await accepted.getByRole('alert').filter({hasText:'O registro foi salvo'}).waitFor();assert.ok(await accepted.getByRole('button',{name:'Adicionar social selling de Leonardo',exact:true}).isDisabled());await accepted.getByRole('button',{name:'Tentar novamente',exact:true}).click();await accepted.getByRole('alert').waitFor({state:'hidden'});assert.equal(await accepted.evaluate(()=>window.__performanceWrites.length),1);await accepted.close();
const slow=await h.open(1440,'&slow=desempenhoLog');await ready(slow);await slow.clock.pauseAt(new Date('2026-09-18T18:05:00Z'));await slow.getByRole('button',{name:'Adicionar social selling de Leonardo',exact:true}).click();assert.ok(await slow.getByRole('button',{name:'Semana',exact:true}).isDisabled());assert.ok(await slow.getByRole('button',{name:'Adicionar social selling de Leonardo',exact:true}).isDisabled());await slow.clock.fastForward(2100);await slow.getByText('Registro atualizado',{exact:true}).waitFor();assert.equal(await slow.evaluate(()=>window.__performanceWrites.length),1);await slow.close();
const stale=await h.open(1440,'&slow=desempenhoLog');await ready(stale);await stale.clock.pauseAt(new Date('2026-09-18T18:05:00Z'));await stale.getByRole('button',{name:'Adicionar social selling de Leonardo',exact:true}).click();await stale.getByRole('button',{name:'Trocar de produto: LeverAds'}).click();await stale.getByRole('button',{name:'Elo',exact:true}).click();await stale.getByText('Nenhum SDR neste produto',{exact:true}).waitFor({state:'attached'});await stale.clock.fastForward(2100);await stale.clock.resume();await stale.getByText('Nenhum SDR neste produto',{exact:true}).waitFor();assert.equal(await stale.getByRole('button',{name:'Detalhes de Leonardo',exact:true}).count(),0);assert.equal(await stale.evaluate(()=>window.__performanceWrites[0].saas),'leverads');await stale.close();
for(const[width,q]of [[390,''],[1024,''],[1440,'&theme=dark'],[1440,'&empty'],[1440,'&viewer'],[1440,'&socialFail']]){const page=await h.open(width,q);if(q.includes('empty'))await page.getByText('Nenhum SDR neste produto',{exact:true}).waitFor();else await ready(page);if(q.includes('viewer'))assert.equal(await page.getByRole('button',{name:'Detalhes de Lucas',exact:true}).count(),0);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await h.capture(page,`state-${width}-${q||'responsive'}`);if(!q.includes('empty')){await page.getByRole('button',{name:'Detalhes de Leonardo',exact:true}).click();await h.capture(page,`detail-${width}-${q||'responsive'}`);}await page.close();}
assert.deepEqual(h.errors,[]);console.log('Desempenho: geometria, período, detalhes/teclado, cópia, contador único, falha/retry e gravação aceita, permissões, Instagram parcial, mobile e escuro OK.');
}finally{await h.close();}
