import assert from 'node:assert/strict';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('disparos','Disparos',async p=>{await p.getByRole('button',{name:/^Marketing/}).click();await p.getByRole('button',{name:'Disparos',exact:true}).click();});
const tab=(p,name)=>p.locator('.disparos-tabs').getByRole('button',{name,exact:true});
const geometry=[];
async function measure(p,ref){return p.evaluate(ref=>{const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Disparos'&&e.getClientRects().length),head=title.closest('header'),grid=[...document.querySelectorAll(ref?'.cap-2col':'.disparos-grid')].find(e=>e.getClientRects().length);return Object.fromEntries(Object.entries({title,head,left:grid.children[0],right:grid.children[1]}).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,height:r.height}]}));},ref);}
try{
 for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){const p=await h.open(width),ref=await h.open(width,'',true);await p.getByText('Atualizando campanhas…',{exact:true}).waitFor({state:'hidden'});await h.capture(p,`app-${width}`);await h.capture(ref,`reference-${width}`);const row={width,app:await measure(p,false),reference:await measure(ref,true)};geometry.push(row);await h.write('geometry.json',geometry);for(const k of ['title','head','left','right'])for(const d of ['x','y','width','height']){if((k==='title'&&d==='width')||(['left','right'].includes(k)&&d==='height'))continue;assert.ok(Math.abs(row.app[k][d]-row.reference[k][d])<=1,`${width} ${k}.${d}: ${row.app[k][d]} / ${row.reference[k][d]}`);}for(const name of ['Sequências','Templates']){await tab(p,name).click();await h.capture(p,`${name}-${width}`);await ref.getByRole('button',{name,exact:true}).click();await h.capture(ref,`reference-${name}-${width}`);}await p.close();await ref.close();}
 const p=await h.open(1440);await p.getByLabel('Nome da campanha',{exact:true}).fill('Campanha fictícia');await p.getByLabel('Mensagem',{exact:true}).fill('Olá ');await p.getByTitle('Inserir primeiro nome',{exact:true}).click();assert.equal(await p.getByLabel('Mensagem',{exact:true}).inputValue(),'Olá {{nome}}');await p.getByRole('button',{name:'Salvar campanha',exact:true}).click();await p.getByText('campanha salva',{exact:true}).waitFor();await p.getByRole('button',{name:'Abrir próximo WhatsApp ↗',exact:true}).click();await p.getByText(/aberto para envio · continue/).waitFor();assert.equal(await p.evaluate(()=>window.__opened.length),1);await p.getByRole('button',{name:'E-mail',exact:true}).click();await p.getByLabel('Assunto do e-mail',{exact:true}).fill('Assunto');await p.getByLabel('Mensagem',{exact:true}).fill('Olá {{nome}}');p.once('dialog',d=>d.dismiss());await p.getByRole('button',{name:/^Disparar \d+ e-mails/}).click();assert.equal(await p.evaluate(()=>window.__disparosWrites.filter(x=>x==='campaignSendEmail').length),0);p.once('dialog',d=>d.accept());await p.getByRole('button',{name:/^Disparar \d+ e-mails/}).click();await p.getByText(/e-mail\(s\) enviado\(s\)/).waitFor();await p.getByRole('button',{name:'Gerar com IA',exact:true}).click();await p.getByText(/copy gerada pela IA/).waitFor();await p.close();
 const seq=await h.open(1440);await tab(seq,'Sequências').click();await seq.getByRole('button',{name:'Retomada por etapas',exact:true}).click();await seq.getByLabel('Nome da sequência',{exact:true}).fill('Sequência editada');await seq.getByRole('button',{name:'+ e-mail',exact:true}).click();await seq.getByLabel('Assunto do passo 2',{exact:true}).fill('Passo 2');await seq.getByLabel('Mensagem do passo 2',{exact:true}).fill('Olá {{nome}}');await seq.getByRole('button',{name:'salvar sequência',exact:true}).click();await seq.getByText('sequência salva',{exact:true}).waitFor();await seq.getByRole('link',{name:'abrir Whats ↗',exact:true}).evaluate(e=>e.addEventListener('click',event=>event.preventDefault()));await seq.getByRole('link',{name:'abrir Whats ↗',exact:true}).click();await seq.getByText(/nenhum passo de WhatsApp pendente/).waitFor();seq.once('dialog',d=>d.accept());await seq.getByRole('button',{name:'apagar',exact:true}).click();await seq.getByText('sequência apagada',{exact:true}).waitFor();await tab(seq,'Templates').click();await seq.getByLabel('Nome do template',{exact:true}).fill('Template fictício');await seq.getByLabel('Assunto do template',{exact:true}).fill('Assunto');await seq.getByLabel('Mensagem do template',{exact:true}).fill('Mensagem');await seq.getByRole('button',{name:'criar template',exact:true}).click();await seq.getByText('template salvo',{exact:true}).waitFor();await seq.getByText('Template fictício',{exact:true}).waitFor();await seq.close();
 for(const [name,method] of [['Disparos','list:campaigns'],['Sequências','list:sequences'],['Templates','list:drip_templates']]){const page=await h.open(1440,`&failOnce=${method}`);if(name!=='Disparos')await tab(page,name).click();await page.getByRole('button',{name:'Tentar novamente',exact:true}).click();await page.getByRole('alert').waitFor({state:'hidden'});await page.close();}
 const fail=await h.open(1440,'&failOnce=create');await fail.getByLabel('Nome da campanha',{exact:true}).fill('Manter rascunho');await fail.getByRole('button',{name:'Salvar campanha',exact:true}).click();await fail.getByText('Falha simulada na prévia',{exact:true}).waitFor();assert.equal(await fail.getByLabel('Nome da campanha',{exact:true}).inputValue(),'Manter rascunho');await fail.getByRole('button',{name:'Salvar campanha',exact:true}).click();await fail.getByText('campanha salva',{exact:true}).waitFor();await fail.close();
 const slow=await h.open(1440,'&slow=create');await slow.clock.pauseAt(new Date('2026-09-18T18:05:00Z'));await slow.getByRole('button',{name:'Salvar campanha',exact:true}).click();assert.ok(await slow.getByLabel('Nome da campanha',{exact:true}).isDisabled());assert.ok(await tab(slow,'Templates').isDisabled());await slow.clock.fastForward(2100);await slow.getByText('campanha salva',{exact:true}).waitFor();assert.equal(await slow.evaluate(()=>window.__disparosWrites.length),1);await slow.close();
 const discard=await h.open(1440);await tab(discard,'Templates').click();await discard.getByLabel('Nome do template',{exact:true}).fill('Não perder');discard.once('dialog',d=>d.dismiss());await tab(discard,'Sequências').click();assert.equal(await discard.getByLabel('Nome do template',{exact:true}).inputValue(),'Não perder');discard.once('dialog',d=>d.accept());await tab(discard,'Sequências').click();await discard.getByLabel('Nome da sequência',{exact:true}).waitFor();await discard.close();
 const tplFail=await h.open(1440,'&failOnce=update:drip_templates');await tab(tplFail,'Templates').click();await tplFail.getByRole('button',{name:'editar',exact:true}).click();await tplFail.getByLabel('Nome do template',{exact:true}).fill('Editar com segurança');await tplFail.getByRole('button',{name:'salvar',exact:true}).click();await tplFail.getByRole('alert').filter({hasText:'Falha simulada'}).waitFor();assert.equal(await tplFail.getByLabel('Nome do template',{exact:true}).inputValue(),'Editar com segurança');await tplFail.getByRole('button',{name:'salvar',exact:true}).click();await tplFail.getByText('template salvo',{exact:true}).waitFor();tplFail.once('dialog',d=>d.accept());await tplFail.getByRole('button',{name:'apagar',exact:true}).click();await tplFail.getByText('template apagado',{exact:true}).waitFor();await tplFail.close();
 const seqSlow=await h.open(1440,'&slow=create');await tab(seqSlow,'Sequências').click();await seqSlow.getByLabel('Nome da sequência',{exact:true}).fill('Uma gravação');await seqSlow.clock.pauseAt(new Date('2026-09-18T18:05:00Z'));await seqSlow.getByRole('button',{name:'salvar sequência',exact:true}).click();assert.ok(await seqSlow.getByLabel('Nome da sequência',{exact:true}).isDisabled());await seqSlow.waitForFunction(()=>[...document.querySelectorAll('.disparos-tabs button')].every(b=>b.disabled));assert.ok(await tab(seqSlow,'Templates').isDisabled());assert.equal(await seqSlow.locator('.disparos-sequences').count(),1);await seqSlow.clock.fastForward(2100);await seqSlow.getByText('sequência salva',{exact:true}).waitFor();assert.equal(await seqSlow.evaluate(()=>window.__disparosWrites.length),1);await seqSlow.close();
 const campDiscard=await h.open(1440);await campDiscard.getByLabel('Nome da campanha',{exact:true}).fill('Rascunho da campanha');campDiscard.once('dialog',d=>d.dismiss());await campDiscard.getByLabel('Carregar campanha',{exact:true}).selectOption('camp-preview');assert.equal(await campDiscard.getByLabel('Nome da campanha',{exact:true}).inputValue(),'Rascunho da campanha');campDiscard.once('dialog',d=>d.accept());await campDiscard.getByLabel('Carregar campanha',{exact:true}).selectOption('camp-preview');assert.equal(await campDiscard.getByLabel('Nome da campanha',{exact:true}).inputValue(),'Retomada do diagnóstico');await campDiscard.close();
 for(const[width,q]of [[390,''],[1024,''],[1440,'&theme=dark'],[1440,'&empty']]){const page=await h.open(width,q);for(const name of ['Disparos','Sequências','Templates']){await tab(page,name).click();await h.capture(page,`state-${name}-${width}-${q||'responsive'}`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}await page.close();}
 assert.deepEqual(h.errors,[]);console.log('Disparos: público, campanha, prévia/tokens, envio mock, IA, sequências, templates, falha/retry, descarte, espera, mobile e escuro OK.');
}finally{await h.close();}
