import assert from 'node:assert/strict';import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('expenses','Financeiro',async p=>{await p.getByRole('button',{name:/^Geral/}).click();await p.getByRole('button',{name:'Financeiro',exact:true}).click();},{nativeTimers:true});
const tab=(p,name)=>p.getByRole('navigation',{name:'Abas do financeiro'}).getByRole('button',{name,exact:true}).click();
const ready=p=>p.getByRole('heading',{name:'DRE do mês',exact:true}).waitFor();
const geometry=(p,ref)=>p.evaluate(ref=>{const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Financeiro'&&e.getClientRects().length),head=ref?title.closest('header'):title.closest('.capsule-page-head');return Object.fromEntries(Object.entries({title,head}).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,height:r.height}]}));},ref);
try{const gs=[];for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){const p=await h.open(width),r=await h.open(width,'',true);await ready(p);await h.capture(p,`app-${width}`);await h.capture(r,`reference-${width}`);const g={width,app:await geometry(p,false),reference:await geometry(r,true)};gs.push(g);for(const k of ['title','head'])for(const d of ['x','y','height',...(k==='head'?['width']:[])])assert.ok(Math.abs(g.app[k][d]-g.reference[k][d])<1,`${width} ${k}.${d}`);await h.write('geometry.json',gs);await p.close();await r.close();}
const p=await h.open(1440);await ready(p);for(const name of ['Conciliação','A pagar','Folha','Pagamentos','Custos']){await tab(p,name);await p.locator('.finance-content').waitFor();await h.capture(p,`tab-${name}`);}await tab(p,'A pagar');await p.getByRole('textbox',{name:'Descrição da conta',exact:true}).fill('Conta nova revisão');await p.getByRole('spinbutton',{name:'Valor da conta',exact:true}).fill('150');await p.getByRole('button',{name:'lançar',exact:true}).click();await p.locator('.finance-payable-row').filter({hasText:'Conta nova revisão'}).waitFor();const row=p.locator('.finance-payable-row').filter({hasText:'Conta nova revisão'});await row.getByRole('button',{name:'informar pagamento',exact:true}).click();await row.getByRole('button',{name:'reabrir',exact:true}).click();p.once('dialog',d=>d.dismiss());await row.getByRole('button',{name:'excluir',exact:true}).click();await row.waitFor();p.once('dialog',d=>d.accept());await row.getByRole('button',{name:'excluir',exact:true}).click();await row.waitFor({state:'detached'});await tab(p,'Custos');await p.getByRole('textbox',{name:'Descrição',exact:true}).fill('Custo revisão');await p.getByRole('spinbutton').fill('99');await p.getByRole('button',{name:'+ registrar',exact:true}).click();await p.getByText('Custo revisão',{exact:true}).waitFor();p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'Remover Custo revisão',exact:true}).click();await p.getByText('Custo revisão',{exact:true}).waitFor({state:'detached'});await tab(p,'Conciliação');await p.getByRole('button',{name:/^usar sugestão/}).click();await p.getByRole('status').filter({hasText:'regra criada'}).waitFor();await p.getByRole('button',{name:'casar (mesmo valor)',exact:true}).click();await p.getByRole('status').filter({hasText:'conta baixada'}).waitFor();assert.equal(await p.evaluate(()=>window.__finWrites.find(w=>w.method==='link').customer),'fc1');await p.close();
for(const[t,method]of [['resumo','fin'],['resumo','expensesSummary'],['conciliacao','mpPayments'],['custos','expensesSummary'],['pagamentos','mpPayments']]){const p=await h.open(1440,`&tab=${t}&failOnce=${method}`);await p.getByRole('alert').waitFor();await p.getByRole('button',{name:'Tentar novamente',exact:true}).click();await p.locator('.finance-content').waitFor();await p.close();}
for(const t of ['pagar','custos']){const p=await h.open(1440,`&tab=${t}&slow=create`);await p.locator('.finance-content').waitFor();if(t==='pagar'){await p.getByRole('textbox',{name:'Descrição da conta',exact:true}).fill('Uma conta');await p.getByRole('spinbutton',{name:'Valor da conta',exact:true}).fill('100');await p.getByRole('button',{name:'lançar',exact:true}).click();assert.ok(await p.getByRole('textbox',{name:'Descrição da conta',exact:true}).isDisabled());}else{await p.getByRole('textbox',{name:'Descrição',exact:true}).fill('Um custo');await p.getByRole('spinbutton').fill('100');await p.getByRole('button',{name:'+ registrar',exact:true}).click();assert.ok(await p.getByRole('textbox',{name:'Descrição',exact:true}).isDisabled());}await p.waitForFunction(()=>window.__finWrites.length===1);await p.close();}
const partial=await h.open(1440,'&tab=conciliacao&ruleFail');await partial.getByRole('button',{name:/^usar sugestão/}).click();await partial.getByRole('alert').filter({hasText:'Pagamento vinculado; regra não criada'}).waitFor();assert.equal(await partial.getByRole('button',{name:/^usar sugestão/}).count(),0);await partial.close();
for(const[width,q]of [[390,''],[1024,''],[1440,'&theme=dark'],[1440,'&empty'],[1440,'&financeCase=deficit'],[1440,'&financeCase=no-income']]){const p=await h.open(width,q);await ready(p);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await h.capture(p,`state-${width}-${q||'responsive'}`);if(width===390)for(const name of ['Conciliação','A pagar','Folha','Pagamentos','Custos']){await tab(p,name);await p.locator('.finance-content').waitFor();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name);await h.capture(p,`mobile-${name}`);}await p.close();}
assert.deepEqual(h.errors,[]);console.log('Financeiro: seis abas, CRUD custos/contas, baixa/reabertura, confirmação, conciliação/regra parcial, erros/retry, gravação única, déficit/sem receita, mobile/escuro OK.');
}finally{await h.close();}
