import assert from 'node:assert/strict';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('forms','Formulários',async p=>{await p.getByRole('button',{name:/^Marketing/}).click();await p.getByRole('button',{name:'Formulários',exact:true}).click();});
const form=p=>p.locator('.forms-card').filter({hasText:'Diagnóstico de operação'});
const editor=p=>p.locator('.forms-editor');
const preview=async p=>{await p.locator('.forms-preview-status').waitFor({state:'hidden'});await p.frameLocator('iframe[title="Preview do form"]').getByRole('heading').waitFor();};
const geometry=[];
async function measure(p,ref){return p.evaluate(ref=>{const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Formulários'&&e.getClientRects().length),head=title.closest('header'),card=ref?head.parentElement.querySelector('section'):document.querySelector('.forms-card');return Object.fromEntries(Object.entries({title,head,card}).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,height:r.height}]}));},ref);}
try {
 for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){const p=await h.open(width),ref=await h.open(width,'',true);await p.locator('.forms-ab').waitFor();await h.capture(p,`app-${width}`);await h.capture(ref,`reference-${width}`);const row={width,app:await measure(p,false),reference:await measure(ref,true)};geometry.push(row);await h.write('geometry.json',geometry);for(const k of ['title','head','card'])for(const d of ['x','y','width','height']){if((k==='title'&&d==='width')||(k==='card'&&d==='height'))continue;assert.ok(Math.abs(row.app[k][d]-row.reference[k][d])<=1,`${width} ${k}.${d}`);}await form(p).getByRole('button',{name:'Editar',exact:true}).click();await p.getByRole('heading',{name:'Editar formulário',exact:true}).waitFor();await preview(p);await h.capture(p,`editor-${width}`);await ref.getByRole('button',{name:'Editar',exact:true}).first().click();await h.capture(ref,`reference-editor-${width}`);await p.close();await ref.close();}
 const p=await h.open(1440);await form(p).getByRole('button',{name:'Copiar link',exact:true}).click();assert.ok((await p.evaluate(()=>navigator.clipboard.readText())).endsWith('/f/diagnostico-preview'));await form(p).getByRole('button',{name:'Ver respostas →',exact:true}).click();await p.getByRole('button',{name:'Ana Lima ana@example.com',exact:true}).click();await p.locator('.forms-response-detail').waitFor();await p.getByRole('button',{name:/^Nível S e A/}).click();assert.equal(await p.locator('.forms-response-row button').count(),1);await p.getByRole('button',{name:/^Últimas 48h/}).click();assert.equal(await p.locator('.forms-response-row button').count(),1);await h.capture(p,'responses');await p.getByRole('button',{name:'← Formulários',exact:true}).click();await p.locator('.forms-ab').waitFor();await form(p).getByRole('button',{name:'Editar',exact:true}).click();await p.getByLabel('Nome do form',{exact:true}).fill('Diagnóstico revisado');await p.getByLabel('Pergunta 1',{exact:true}).fill('Seu nome completo?');await p.getByRole('button',{name:'Salvar',exact:true}).click();await p.getByRole('heading',{name:'Formulários',exact:true}).waitFor();await p.getByText('Diagnóstico revisado',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>window.__formsWrites[0].patch.questions[0].label),'Seu nome completo?');await p.getByRole('button',{name:'Criar formulário',exact:true}).click();await p.getByRole('button',{name:'Salvar',exact:true}).click();await p.getByRole('alert').waitFor();await p.getByLabel('Nome do form',{exact:true}).fill('Formulário fictício');await p.getByRole('button',{name:'Salvar',exact:true}).click();await p.getByText('Formulário fictício',{exact:true}).waitFor();assert.equal(await p.evaluate(()=>window.__formsWrites.length),2);await p.close();
 for(const method of ['formsOverview','formFunnels','list']){const page=await h.open(1440,`&failOnce=${method}`);if(method==='list')await form(page).getByRole('button',{name:'Ver respostas →',exact:true}).click();const retry=page.getByRole('button',{name:method==='formsOverview'?'Tentar de novo':'Tentar novamente',exact:true}).first();await retry.click();await retry.waitFor({state:'hidden'});await page.close();}
 const fail=await h.open(1440,'&failOnce=update');await form(fail).getByRole('button',{name:'Editar',exact:true}).click();await fail.getByLabel('Nome do form',{exact:true}).fill('Manter o rascunho');await fail.getByRole('button',{name:'Salvar',exact:true}).click();await fail.getByRole('alert').filter({hasText:'Falha simulada'}).waitFor();assert.equal(await fail.getByLabel('Nome do form',{exact:true}).inputValue(),'Manter o rascunho');await fail.getByRole('button',{name:'Salvar',exact:true}).click();await fail.getByText('Manter o rascunho',{exact:true}).waitFor();await fail.close();
 const discard=await h.open(1440);await form(discard).getByRole('button',{name:'Editar',exact:true}).click();await discard.getByLabel('Nome do form',{exact:true}).fill('Rascunho não salvo');discard.once('dialog',d=>d.dismiss());await discard.getByRole('button',{name:'Cancelar',exact:true}).click();assert.equal(await discard.getByLabel('Nome do form',{exact:true}).inputValue(),'Rascunho não salvo');discard.once('dialog',d=>d.accept());await discard.getByRole('button',{name:'Cancelar',exact:true}).click();await discard.getByRole('heading',{name:'Formulários',exact:true}).waitFor();await discard.close();
 const previewFail=await h.open(1440,'&failOnce=formPreview');await form(previewFail).getByRole('button',{name:'Editar',exact:true}).click();await previewFail.getByRole('alert').filter({hasText:'prévia'}).getByRole('button',{name:'Tentar novamente',exact:true}).click();await preview(previewFail);await previewFail.close();
 const slow=await h.open(1440,'&slow=update');await form(slow).getByRole('button',{name:'Editar',exact:true}).click();await slow.getByLabel('Nome do form',{exact:true}).fill('Salvar uma vez');await slow.clock.pauseAt(new Date('2026-09-18T18:05:00Z'));await slow.getByRole('button',{name:'Salvar',exact:true}).click();assert.ok(await slow.getByRole('button',{name:'Cancelar',exact:true}).isDisabled());assert.ok(await slow.getByRole('button',{name:'Salvando…',exact:true}).isDisabled());assert.ok(await slow.getByLabel('Nome do form',{exact:true}).isDisabled());await slow.clock.fastForward(2100);await slow.getByText('Salvar uma vez',{exact:true}).waitFor();assert.equal(await slow.evaluate(()=>window.__formsWrites.length),1);await slow.close();
 const publish=await h.open(1440);await form(publish).getByTitle('despublicar',{exact:true}).click();await form(publish).getByRole('button',{name:'Publicar',exact:true}).waitFor();await form(publish).getByRole('button',{name:'Publicar',exact:true}).click();await form(publish).getByRole('button',{name:'Copiar link',exact:true}).waitFor();assert.equal(await publish.evaluate(()=>window.__formsWrites.length),2);await publish.close();
 for(const[width,q]of [[390,''],[1024,''],[1440,'&theme=dark'],[1440,'&empty']]){const page=await h.open(width,q);await h.capture(page,`state-${width}-${q||'responsive'}`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.getByRole('button',{name:'Criar formulário',exact:true}).click();await preview(page);await h.capture(page,`editor-${width}-${q||'responsive'}`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.close();}
 assert.deepEqual(h.errors,[]);console.log('Formulários: lista, clipboard, respostas/filtros, edição/criação, falha/retry, descarte, mobile e escuro OK.');
}finally {await h.close();}
