import assert from 'node:assert/strict';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('integrations','Análise de Integração',async p=>{await p.getByRole('button',{name:/^Análises/}).click();await p.getByRole('button',{name:'Análise de Integração',exact:true}).click();});
const geometry=[];
const measure=(p,ref)=>p.evaluate(ref=>{const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Análise de Integração'&&e.getClientRects().length),head=title.closest('header'),sections=head.parentElement.querySelectorAll('section'),risk=ref?sections[0]:document.querySelector('.integrations-risk'),delays=ref?sections[1]:document.querySelector('.integrations-delays');return Object.fromEntries(Object.entries({title,head,risk,delays}).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,height:r.height}]}));},ref);
try{
for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){const p=await h.open(width),ref=await h.open(width,'',true);await p.locator('.integrations-risk').waitFor();await h.capture(p,`app-${width}`);await h.capture(ref,`reference-${width}`);const row={width,app:await measure(p,false),reference:await measure(ref,true)};geometry.push(row);await h.write('geometry.json',geometry);for(const k of ['title','head','risk','delays'])for(const d of ['x','y','width','height']){if(k==='title'&&d==='width')continue;assert.ok(Math.abs(row.app[k][d]-row.reference[k][d])<=1,`${width} ${k}.${d}: ${row.app[k][d]} / ${row.reference[k][d]}`);}await p.close();await ref.close();}
for(const selector of ['.integrations-risk button','.integrations-delays button','.call-recent-row>button']){const p=await h.open(1440);await p.locator(selector).first().focus();await p.keyboard.press('Enter');await p.getByRole('dialog').waitFor();await p.close();}
const fail=await h.open(1440,'&failOnce=integrationAnalysis');await fail.getByRole('alert').getByRole('button',{name:'Tentar novamente'}).click();await fail.locator('.call-distribution').waitFor();await fail.close();
const slow=await h.open(1440,'&failOnce=integrationAnalysis&slow=integrationAnalysis');await slow.getByRole('alert').waitFor();await slow.clock.pauseAt(new Date('2026-09-18T18:05:00Z'));await slow.getByRole('button',{name:'Tentar novamente'}).click();await slow.getByRole('status').filter({hasText:'Carregando integrações'}).waitFor();await slow.clock.fastForward(2100);await slow.locator('.call-distribution').waitFor();await slow.close();
const workspace=await h.open(1440);await workspace.locator('.integrations-risk').waitFor();await workspace.getByRole('button',{name:'Trocar de produto: LeverAds'}).click();await workspace.getByRole('button',{name:'Elo',exact:true}).click();await workspace.getByText('Nenhuma integração resumida ainda',{exact:true}).waitFor();assert.equal(await workspace.locator('.integrations-risk').count(),0);assert.equal(await workspace.evaluate(()=>window.__integrationReads.at(-1)),'elo');await workspace.close();
for(const[width,q]of [[390,''],[1024,''],[1440,'&theme=dark'],[1440,'&empty'],[1440,'&small'],[1440,'&safe'],[1440,'&missing']]){const p=await h.open(width,q);if(q.includes('empty'))await p.getByText('Nenhuma integração resumida ainda',{exact:true}).waitFor();else await p.locator('.call-distribution').waitFor();if(q.includes('small'))await p.locator('.call-analysis-warning').waitFor();if(q.includes('safe'))assert.equal(await p.locator('.integrations-risk,.integrations-delays').count(),0);if(q.includes('missing'))assert.ok(await p.locator('.integrations-risk button').isDisabled());assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await h.capture(p,`state-${width}-${q||'responsive'}`);if(!q.includes('empty')){assert.equal(await p.getByRole('link',{name:/Abrir gravação/}).first().getAttribute('target'),'_blank');await p.locator('.call-analysis-recent').scrollIntoViewIfNeeded();await h.capture(p,`recent-${width}-${q||'responsive'}`);}await p.close();}
assert.deepEqual(h.errors,[]);console.log('Integração: geometria, risco/atraso/lead por teclado, gravação, vazio, base pequena, sem risco, indisponível, retry, carga, produto, mobile e escuro OK.');
}finally{await h.close();}
