import assert from 'node:assert/strict';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('metas','Metas',async p=>{await p.getByRole('button',{name:/^Geral/}).click();await p.getByRole('button',{name:'Metas',exact:true}).click();},{nativeTimers:true});
const ready=async p=>p.getByRole('spinbutton',{name:'Meta de venda do mês',exact:true}).waitFor();
const geo=(p,ref)=>p.evaluate(ref=>{const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Metas'&&e.getClientRects().length),head=ref?title.closest('header'):title.closest('.capsule-page-head'),card=ref?head.nextElementSibling:document.querySelector('.metas-fields>.metas-card');return Object.fromEntries(Object.entries({title,head,card}).map(([k,e])=>{const b=e.getBoundingClientRect();return[k,{x:b.x,y:b.y,width:b.width,height:b.height}]}));},ref);
try{
const measures=[];
for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){const p=await h.open(width),r=await h.open(width,'',true);await ready(p);await h.capture(p,`app-${width}`);await h.capture(r,`reference-${width}`);const g={width,app:await geo(p,false),reference:await geo(r,true)};measures.push(g);await h.write('geometry.json',measures);for(const k of ['head','title','card'])for(const d of ['x','y','width']){if(k==='title'&&d==='width')continue;assert.ok(Math.abs(g.app[k][d]-g.reference[k][d])<1,`${width} ${k}.${d}: ${g.app[k][d]} vs ${g.reference[k][d]}`);}await p.close();await r.close();}
const p=await h.open(1440);await ready(p);await p.getByRole('spinbutton',{name:'Meta de venda do mês',exact:true}).fill('150000');await p.getByRole('button',{name:'derivar metas do pace',exact:true}).click();await p.getByRole('button',{name:'definir os 3 meses',exact:true}).click();await p.getByRole('spinbutton',{name:'Contratos de Leonardo',exact:true}).fill('');await p.getByRole('button',{name:'salvar metas',exact:true}).click();await p.getByRole('status').filter({hasText:'metas salvas'}).waitFor();const w=await p.evaluate(()=>window.__metasWrites[0]);assert.equal(w.company.months['2026-10'],'165000');assert.ok(w.goals.some(g=>g.key==='leo'&&g.metric==='won'&&g.target===''));assert.ok(!w.goals.some(g=>g.scope==='role'&&g.metric==='won'));assert.equal(w.goals.find(g=>g.metric==='contacted').target,'260');await p.getByRole('combobox',{name:'Nível de Leonardo'}).selectOption('2');await p.getByRole('status').filter({hasText:'agora é'}).waitFor();await p.getByRole('button',{name:'+ outra meta por pessoa',exact:true}).click();await p.getByRole('spinbutton',{name:'Valor do ajuste 1',exact:true}).fill('50');await p.getByRole('button',{name:'descartar',exact:true}).click();assert.equal(await p.getByRole('spinbutton',{name:'Valor do ajuste 1',exact:true}).count(),0);await p.close();
for(const query of ['&failOnce=saveMetas','&slow=saveMetas','&refreshFail']){const page=await h.open(1440,query);await ready(page);await page.getByRole('spinbutton',{name:'Meta de venda do mês',exact:true}).fill('160000');await page.getByRole('button',{name:'salvar metas',exact:true}).click();if(query.includes('failOnce')){await page.getByRole('alert').filter({hasText:'Falha simulada'}).waitFor();assert.equal(await page.getByRole('spinbutton',{name:'Meta de venda do mês',exact:true}).inputValue(),'160000');await page.getByRole('button',{name:'salvar metas',exact:true}).click();}else if(query.includes('slow')){assert.ok(await page.getByRole('spinbutton',{name:'Meta de venda do mês',exact:true}).isDisabled());}else{await page.getByRole('button',{name:'Atualizar metas gravadas',exact:true}).click();}await page.getByRole('status').filter({hasText:'metas salvas'}).waitFor();assert.equal(await page.evaluate(()=>window.__metasWrites.length),1);await page.close();}
for(const method of ['metas','pipelinePace']){const page=await h.open(1440,`&failOnce=${method}`);await page.getByRole('button',{name:method==='metas'?'Tentar novamente':'Recarregar réguas',exact:true}).click();await ready(page);await page.getByText('Régua de receita',{exact:true}).waitFor();await page.close();}
const level=await h.open(1440,'&failOnce=updateUser');await ready(level);await level.getByRole('combobox',{name:'Nível de Leonardo'}).selectOption('2');await level.getByRole('alert').filter({hasText:'nível não salvo'}).waitFor();assert.equal(await level.getByRole('combobox',{name:'Nível de Leonardo'}).inputValue(),'1');await level.close();
for(const[width,q]of [[390,''],[1024,''],[1440,'&theme=dark'],[1440,'&empty'],[1440,'&readonly']]){const page=await h.open(width,q);await ready(page);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(q.includes('readonly'))assert.equal(await page.getByRole('combobox',{name:'Nível de Leonardo'}).count(),0);await h.capture(page,`state-${width}-${q||'responsive'}`);await page.getByRole('heading',{name:'Agenda de metas',exact:true}).scrollIntoViewIfNeeded();await h.capture(page,`agenda-${width}-${q||'responsive'}`);await page.close();}
assert.deepEqual(h.errors,[]);console.log('Metas: geometria, campos, derivações, agenda, excluir ajuste, nível/rollback, falhas/nova tentativa, salvamento único, releitura sem reenviar, mobile e escuro OK.');
}finally{await h.close();}
