import assert from 'node:assert/strict';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('mindmaps','Mapas mentais',async p=>{await p.getByRole('button',{name:/^Geral/}).click();await p.getByRole('button',{name:'Mapas mentais',exact:true}).click();},{nativeTimers:true});
const ready=async p=>{await p.locator('.mindmaps-node[data-id="r"]').waitFor();await p.locator('.mindmaps-canvas[data-fitted=true]').waitFor();await p.locator('.mindmaps-canvas').evaluate(async e=>Promise.all(e.getAnimations({subtree:true}).map(a=>a.finished.catch(()=>{}))));};
const edit=async(p,text)=>{await p.locator('.mindmaps-node[data-id="r"]').dblclick();await p.getByRole('textbox',{name:'Texto do nó',exact:true}).fill(text);await p.getByRole('textbox',{name:'Texto do nó',exact:true}).press('Escape');};
const saved=async p=>p.locator('.mindmaps-save').filter({hasText:/^salvo$/}).waitFor();
const geometry=[];
const measure=(p,ref)=>p.evaluate(ref=>{const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Mapas mentais'&&e.getClientRects().length),head=ref?title.closest('header'):document.querySelector('.mindmaps-head');const body=ref?head.nextElementSibling:document.querySelector('.mindmaps-body');const list=body.querySelector('aside'),workspace=ref?body.querySelector(':scope>section'):document.querySelector('.mindmaps-workspace');return Object.fromEntries(Object.entries({title,head,body,list,workspace}).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,height:r.height}]}));},ref);
try{
for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){const p=await h.open(width),ref=await h.open(width,'',true);await ready(p);await h.capture(p,`app-${width}`);await h.capture(ref,`reference-${width}`);const row={width,app:await measure(p,false),reference:await measure(ref,true)};geometry.push(row);for(const key of ['title','head','body','list','workspace'])for(const d of ['x','y','width','height']){if((key==='title'&&d==='width')||(key==='list'&&d==='height'))continue;assert.ok(Math.abs(row.app[key][d]-row.reference[key][d])<=1,`${width} ${key}.${d}`);}await h.write('geometry.json',geometry);await p.close();await ref.close();}
const p=await h.open(1440);await ready(p);assert.equal(await p.getByRole('button',{name:/Mapa de Elo/}).count(),0);await edit(p,'Funil revisado');await p.waitForFunction(()=>window.__mapWrites.some(w=>w.body?.nodes?.[0]?.text==='Funil revisado'));await saved(p);await p.getByRole('button',{name:/^Desfazer/}).click();await p.waitForFunction(()=>window.__mapWrites.at(-1)?.body?.nodes?.[0]?.text==='Funil LeverAds');await p.getByRole('button',{name:/^Refazer/}).click();await p.waitForFunction(()=>window.__mapWrites.at(-1)?.body?.nodes?.[0]?.text==='Funil revisado');await p.getByRole('button',{name:'Esboço',exact:true}).click();await h.capture(p,'outline');await p.getByRole('button',{name:'Mapa',exact:true}).click();await p.locator('.mindmaps-node[data-id="r"]').focus();await p.getByRole('button',{name:'Nota (⌥⇧N)',exact:true}).click();await p.getByRole('textbox',{name:'Nota do nó',exact:true}).fill('Contexto de revisão');await p.getByRole('dialog',{name:'Editar nó',exact:true}).getByRole('button',{name:/^salvar/}).click();await p.waitForFunction(()=>window.__mapWrites.at(-1)?.body?.nodes?.[0]?.note==='Contexto de revisão');await p.getByRole('button',{name:'Mais ferramentas',exact:true}).click();await p.getByRole('combobox',{name:'Layout automático do mapa'}).selectOption('radial');await p.waitForFunction(()=>window.__mapWrites.at(-1)?.body?.layout==='radial');await p.getByRole('textbox',{name:'Buscar no mapa',exact:true}).fill('Entrada');await p.getByText('1 resultados',{exact:true}).waitFor();await p.getByRole('button',{name:'Limpar busca',exact:true}).click();await p.getByRole('button',{name:'Exportar mapa',exact:true}).click();await p.getByRole('menuitem',{name:'Copiar esboço (Markdown)',exact:true}).click();assert.match(await p.evaluate(()=>navigator.clipboard.readText()),/Funil revisado/);await p.getByRole('button',{name:/^Modo foco/}).click();await p.getByRole('button',{name:'sair do foco',exact:true}).click();await p.close();
const rename=await h.open(1440,'&failOnce=update');await ready(rename);const name=rename.getByRole('textbox',{name:'Nome do mapa',exact:true});await name.fill('Nome revisado');await name.press('Enter');await rename.getByRole('button',{name:'Nome não salvo · tentar novamente',exact:true}).click();await rename.waitForFunction(()=>window.__mapWrites.some(w=>w.body?.name==='Nome revisado'));await edit(rename,'Depois de renomear');await rename.waitForFunction(()=>window.__mapWrites.some(w=>w.body?.nodes?.[0]?.text==='Depois de renomear'));assert.equal(await rename.getByText('conflito',{exact:true}).count(),0);await rename.close();
const failed=await h.open(1440,'&failOnce=update');await ready(failed);await edit(failed,'Preservar texto');await failed.getByRole('alert').filter({hasText:'O mapa não foi salvo'}).getByRole('button',{name:'Tentar novamente',exact:true}).click();await failed.waitForFunction(()=>window.__mapWrites.some(w=>w.body?.nodes?.[0]?.text==='Preservar texto'));await failed.close();
const slow=await h.open(1440,'&slow=update');await ready(slow);await edit(slow,'Primeira edição');await slow.locator('.mindmaps-save').filter({hasText:'salvando'}).waitFor();await edit(slow,'Edição mais recente');await slow.getByRole('button',{name:/^Plano do trimestre/}).click();await slow.getByRole('textbox',{name:'Nome do mapa',exact:true}).filter({visible:true}).waitFor();await slow.waitForFunction(()=>document.querySelector('.mindmaps-name input')?.value==='Plano do trimestre');assert.deepEqual(await slow.evaluate(()=>window.__mapWrites.filter(w=>w.body?.nodes).map(w=>[w.body.baseVersion,w.body.nodes[0].text])),[[1,'Primeira edição'],[2,'Edição mais recente']]);await slow.close();
const conflict=await h.open(1440,'&conflict');await ready(conflict);await edit(conflict,'Minha edição');await conflict.getByRole('alert').filter({hasText:'editou este mapa'}).waitFor();await conflict.getByRole('button',{name:'Recarregar (perde o que mudei)',exact:true}).click();await conflict.getByRole('button',{name:'Atualizado por outra pessoa',exact:true}).waitFor();await conflict.close();
const read=await h.open(1440,'&failOnce=list');await read.getByRole('alert').getByRole('button',{name:'Tentar novamente',exact:true}).click();await ready(read);await read.close();
const create=await h.open(1440,'&slow=create');await ready(create);await create.getByRole('button',{name:'Criar mapa',exact:true}).click();assert.ok(await create.getByRole('button',{name:'Criar mapa',exact:true}).isDisabled());await create.waitForFunction(()=>window.__mapWrites.some(w=>w.method==='create'));assert.equal(await create.evaluate(()=>window.__mapWrites.filter(w=>w.method==='create').length),1);await create.getByRole('textbox',{name:'Nome do mapa',exact:true}).fill('Mapa novo de revisão');await create.getByRole('textbox',{name:'Nome do mapa',exact:true}).press('Enter');await create.getByRole('button',{name:'Criar primeiro nó',exact:true}).click();await create.getByRole('textbox',{name:'Texto do nó',exact:true}).fill('Ideia inicial');await create.getByRole('textbox',{name:'Texto do nó',exact:true}).press('Escape');await create.waitForFunction(()=>window.__mapWrites.some(w=>w.body?.nodes?.[0]?.text==='Ideia inicial'));await create.close();
for(const[width,q]of [[390,''],[1024,''],[1440,'&theme=dark'],[1440,'&empty']]){const page=await h.open(width,q);if(q.includes('empty'))await page.getByRole('button',{name:'Criar primeiro mapa',exact:true}).waitFor();else await ready(page);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await h.capture(page,`state-${width}-${q||'responsive'}`);if(width===390){await page.waitForFunction(()=>{const b=document.querySelector('.mindmaps-canvas').getBoundingClientRect();return [...document.querySelectorAll('.mindmaps-node')].every(e=>{const r=e.getBoundingClientRect();return r.left>=b.left-1&&r.right<=b.right+1&&r.top>=b.top-1&&r.bottom<=b.bottom+1;});});await page.locator('.mindmaps-node[data-id="r"]').click();await page.getByRole('button',{name:'Nota (⌥⇧N)',exact:true}).click();await page.getByRole('dialog',{name:'Editar nó',exact:true}).getByRole('button',{name:'Fechar',exact:true}).click();await page.getByRole('button',{name:'Mostrar lista de mapas',exact:true}).click();await page.getByRole('button',{name:/^Plano do trimestre/}).click();await page.getByRole('button',{name:'Plano do trimestre',exact:true}).waitFor();await page.getByRole('button',{name:'Mais ferramentas',exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}await page.close();}
const operations=await h.open(1440);await ready(operations);await operations.getByRole('button',{name:'Duplicar Funil LeverAds',exact:true}).click();await operations.waitForFunction(()=>document.querySelector('.mindmaps-name input')?.value==='Funil LeverAds (cópia)');assert.equal(await operations.evaluate(()=>window.__mapWrites.find(w=>w.method==='create').body.nodes.length),7);await operations.getByRole('button',{name:'Ações de Funil LeverAds (cópia)',exact:true}).click();operations.once('dialog',d=>d.dismiss());await operations.getByRole('menuitem',{name:'Apagar mapa',exact:true}).click();assert.equal(await operations.evaluate(()=>window.__mapWrites.filter(w=>w.method==='remove').length),0);await operations.getByRole('button',{name:'Ações de Funil LeverAds (cópia)',exact:true}).click();operations.once('dialog',d=>d.accept());await operations.getByRole('menuitem',{name:'Apagar mapa',exact:true}).click();await operations.waitForFunction(()=>window.__mapWrites.some(w=>w.method==='remove'));await operations.close();
assert.deepEqual(h.errors,[]);console.log('Mapas mentais: layout, esboço, busca, exportação, foco, autosave/versionamento, rascunho recente, rename/retry, conflito, criação única, vazio, mobile e escuro OK.');
}finally{await h.close();}
