import assert from 'node:assert/strict';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('offers','Links de pagamento',async p=>{await p.getByRole('button',{name:/^Comercial/}).click();await p.getByRole('button',{name:'Links de pagamento',exact:true}).click();});
const measurements=[];
async function measure(page,reference,expanded=false) {return page.evaluate(({reference,expanded})=>{
 const h1=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Links de pagamento'&&e.getClientRects().length),root=reference?h1.parentElement.parentElement.parentElement:document.querySelector('.offers-page');
 const header=root.children[0],summary=root.children[1],card=root.children[2],toolbar=card.children[0],table=card.children[1].children[0],head=table.children[0],row=reference?table.children[1].children[0]:table.children[1];
 const values=reference?summary.children[1]:summary.querySelector('.offers-summary-values'),bar=reference?summary.children[2]:summary.querySelector('.offers-bar'),legend=reference?summary.children[3]:summary.querySelector('.offers-legend');
 const elements={title:h1,header,summary,values,waiting:values.children[0],received:values.children[1],generated:values.children[2],failed:values.children[3],bar,legend,card,toolbar,search:toolbar.lastElementChild,head,row,...Object.fromEntries([...row.children].map((e,i)=>[`cell${i}`,e]))};
 if(expanded){elements.links=reference?table.children[1].children[1]:table.querySelector('.offers-links');elements.link=elements.links.children[0];}
 return Object.fromEntries(Object.entries(elements).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,height:r.height}];}));
},{reference,expanded});}
async function compare(app,ref,width,expanded=false){const pair={width,expanded,app:await measure(app,false,expanded),reference:await measure(ref,true,expanded)};measurements.push(pair);await h.write('geometry.json',measurements);for(const[name,box]of Object.entries(pair.reference))for(const[k,v]of Object.entries(box))assert.ok(Math.abs(v-pair.app[name][k])<=1,`${width} ${name}.${k}: ${pair.app[name][k]} vs ${v}`);}
try {
 for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]) {
  const app=await h.open(width),ref=await h.open(width,'',true);await app.locator('.offers-group').first().waitFor();await ref.evaluate(async()=>{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));await Promise.all(document.getAnimations().filter(a=>a.effect?.getComputedTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));});
  await h.capture(app,`app-${width}`);await h.capture(ref,`reference-${width}`);await compare(app,ref,width);
  await app.getByRole('button',{name:'Expandir links de Galante Holding',exact:true}).click();await ref.getByText('Galante Holding',{exact:true}).filter({visible:true}).click();await h.capture(app,`expanded-${width}`);await h.capture(ref,`reference-expanded-${width}`);await compare(app,ref,width,true);await app.close();await ref.close();
 }
 const p=await h.open(1440);await p.locator('.offers-group').first().waitFor();assert.equal(await p.locator('.offers-group').count(),4);
 assert.equal(await p.getByText(/fora do período: amplie/).count(),0);
 const tabs=p.locator('.offers-tabs'),search=p.getByRole('textbox',{name:'Buscar links'});
 await tabs.getByRole('button',{name:/^Pagos/}).click();assert.equal(await p.locator('.offers-group').count(),9);
 await tabs.getByRole('button',{name:/^Recusados/}).click();assert.equal(await p.locator('.offers-group').count(),1);
 await tabs.getByRole('button',{name:/^Todos/}).click();assert.equal(await p.locator('.offers-group').count(),12);
 await search.fill('inexistente');await p.getByText('nenhum cliente com esse filtro ·').waitFor();await p.getByRole('button',{name:'Limpar',exact:true}).click();assert.equal(await p.locator('.offers-group').count(),12);
 await search.fill('Galante');await p.getByRole('button',{name:'Ver quem está devendo →',exact:true}).click();assert.equal(await search.inputValue(),'');assert.equal(await p.locator('.offers-group').count(),4);
 const group=p.locator('.offers-group').first();assert.ok((await group.getByRole('link',{name:'Cobrar'}).getAttribute('href')).includes('https%3A%2F%2Fmpago.la%2F2100'));
 await group.getByRole('button',{name:'Copiar',exact:true}).click();await group.getByRole('button',{name:'Copiado ✓',exact:true}).waitFor();assert.equal(await p.evaluate(()=>navigator.clipboard.readText()),'https://mpago.la/2100');
 const expand=p.getByRole('button',{name:'Expandir links de Galante Holding'});await expand.focus();await p.keyboard.press('Enter');const link=p.locator('[data-link="l0-0"]');await link.waitFor();const pay=link.getByRole('button',{name:'Dar baixa'});await pay.click();let modal=p.getByRole('dialog',{name:'Marcar como pago',exact:true});await modal.waitFor();await modal.getByPlaceholder('opcional: comprovante, quem confirmou…').fill('Pago na revisão');await modal.getByRole('button',{name:'Cancelar',exact:true}).click();assert.equal(await pay.evaluate(e=>e===document.activeElement),true);await pay.click();await modal.getByRole('button',{name:'marcar como pago',exact:true}).click();await modal.waitFor({state:'hidden'});await link.getByText('baixa manual',{exact:true}).waitFor();assert.ok(await p.evaluate(()=>window.__reviewMutations.some(m=>m.method==='payPaymentLink'&&m.id==='l0-0')));
 await link.getByRole('button',{name:'⋯',exact:true}).click();p.once('dialog',d=>d.dismiss());await p.getByRole('button',{name:'Desfazer baixa',exact:true}).click();assert.equal(await link.getByText('baixa manual',{exact:true}).isVisible(),true);await link.getByRole('button',{name:'⋯',exact:true}).click();p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'Desfazer baixa',exact:true}).click();await pay.waitFor();
 await p.getByRole('button',{name:'Expandir links de Studio Kern'}).click();p.once('dialog',d=>d.accept());await p.locator('[data-link="l1-0"]').getByRole('button',{name:'Dar baixa'}).click();await p.waitForFunction(()=>window.__reviewMutations.some(m=>m.method==='payInvoice'));
 await tabs.getByRole('button',{name:/^Todos/}).click();await p.getByRole('button',{name:'Expandir links de Oficina Prado'}).click();await p.locator('[data-link="l6-0"]').getByRole('button',{name:'⋯'}).click();p.once('dialog',d=>d.accept());await p.getByRole('button',{name:'Desfazer baixa',exact:true}).click();await p.waitForFunction(()=>window.__reviewMutations.some(m=>m.method==='unpayInvoice'));
 await p.getByRole('combobox',{name:'Quem gerou o link'}).focus();await p.getByRole('combobox',{name:'Quem gerou o link'}).selectOption('lucas');await p.waitForFunction(()=>window.__reviewReads.at(-1)?.by==='lucas');await p.locator('.offers-card[aria-busy=false]').waitFor();assert.equal(await p.getByRole('combobox',{name:'Quem gerou o link'}).evaluate(e=>e===document.activeElement),true);assert.equal(await p.locator('.offers-group').filter({hasText:'Galante Holding'}).count(),0);await p.getByRole('combobox',{name:'Quem gerou o link'}).selectOption('');await p.locator('.offers-group').filter({hasText:'Galante Holding'}).waitFor();
 await p.getByRole('button',{name:'Gerar link',exact:true}).click();const create=p.getByRole('dialog',{name:'Link de pagamento',exact:true});await create.getByRole('button',{name:/^Fernanda Luz/}).click();await create.getByRole('button',{name:'gerar link',exact:true}).click();await create.getByRole('alert').waitFor();await create.getByRole('spinbutton',{name:'Valor da cobrança (R$)',exact:true}).fill('1234.56');await create.getByRole('button',{name:'gerar link',exact:true}).click();await create.getByText('https://mpago.la/review-new',{exact:true}).waitFor();assert.ok(await p.evaluate(()=>window.__reviewMutations.some(m=>m.method==='mpLeadLink'&&m.body.amount===1234.56&&m.body.origin==='tela')));await create.getByRole('button',{name:'Fechar',exact:true}).click();assert.equal(await p.getByRole('button',{name:'Gerar link',exact:true}).evaluate(e=>e===document.activeElement),true);await p.close();
 const failure=await h.open(1440,'&failOnce=paymentLinks');await failure.getByRole('alert').waitFor();assert.equal(await failure.locator('.offers-summary').count(),0);await failure.getByRole('button',{name:'Tentar novamente'}).click();await failure.locator('.offers-group').first().waitFor();await h.capture(failure,'read-retry');await failure.close();
 const slow=await h.open(1440,'&failOnce=paymentLinks&holdHistory');await slow.getByRole('alert').waitFor();await slow.getByRole('button',{name:'Tentar novamente'}).click();await slow.getByText('Carregando histórico…',{exact:true}).waitFor();await slow.getByRole('button',{name:'Gerar link',exact:true}).click();await slow.getByRole('dialog',{name:'Link de pagamento'}).waitFor();await slow.close();
 const payFail=await h.open(1440,'&failOnce=payPaymentLink');await payFail.getByRole('button',{name:'Expandir links de Galante Holding'}).click();await payFail.locator('[data-link="l0-0"]').getByRole('button',{name:'Dar baixa'}).click();modal=payFail.getByRole('dialog',{name:'Marcar como pago'});await modal.getByPlaceholder('opcional: comprovante, quem confirmou…').fill('Manter observação');await modal.getByRole('button',{name:'marcar como pago',exact:true}).click();await modal.getByRole('alert').waitFor();assert.equal(await modal.getByPlaceholder('opcional: comprovante, quem confirmou…').inputValue(),'Manter observação');await modal.getByRole('button',{name:'marcar como pago',exact:true}).click();await modal.waitFor({state:'hidden'});await payFail.close();
 const hold=await h.open(1440,'&holdPay');await hold.getByRole('button',{name:'Expandir links de Galante Holding'}).click();await hold.locator('[data-link="l0-0"]').getByRole('button',{name:'Dar baixa'}).click();modal=hold.getByRole('dialog',{name:'Marcar como pago'});await modal.getByRole('button',{name:'marcar como pago',exact:true}).click();assert.equal(await modal.getByRole('button',{name:'Cancelar',exact:true}).isEnabled(),false);await hold.keyboard.press('Escape');assert.equal(await modal.isVisible(),true);await hold.evaluate(()=>window.__releasePay());await modal.waitFor({state:'hidden'});assert.equal(await hold.evaluate(()=>window.__reviewMutations.length),1);await hold.close();
 const createFail=await h.open(1440,'&failOnce=mpLeadLink');await createFail.getByRole('button',{name:'Gerar link',exact:true}).click();const creation=createFail.getByRole('dialog',{name:'Link de pagamento'});await creation.getByRole('button',{name:/^Fernanda Luz/}).click();await creation.getByRole('spinbutton',{name:'Valor da cobrança (R$)',exact:true}).fill('24000');await creation.getByRole('button',{name:'gerar link',exact:true}).click();await creation.getByRole('alert').waitFor();assert.equal(await creation.getByRole('spinbutton',{name:'Valor da cobrança (R$)',exact:true}).inputValue(),'24000');await creation.getByRole('button',{name:'gerar link',exact:true}).click();await creation.getByText('https://mpago.la/review-new',{exact:true}).waitFor();await createFail.close();
 const empty=await h.open(1440,'&state=empty');await empty.getByText('Nenhum link de pagamento no período.',{exact:true}).waitFor();await h.capture(empty,'empty');await empty.close();
 const disconnected=await h.open(1440,'&disconnected&closer');assert.equal(await disconnected.getByRole('button',{name:'Gerar link',exact:true}).isEnabled(),false);assert.equal(await disconnected.getByRole('combobox',{name:'Quem gerou o link'}).count(),0);await disconnected.close();
 const mobile=await h.open(390);await mobile.locator('.offers-group').first().waitFor();assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await mobile.locator('.offers-card .tbl-x').evaluate(e=>e.scrollWidth>e.clientWidth));await h.capture(mobile,'mobile');await mobile.getByRole('button',{name:'Gerar link',exact:true}).click();const mobileModal=mobile.getByRole('dialog',{name:'Link de pagamento'});await mobileModal.getByRole('button',{name:'Cliente',exact:true}).click();await mobileModal.getByPlaceholder('buscar cliente…').fill('Galante');await mobileModal.getByRole('button',{name:/^Galante Holding/}).click();await mobileModal.getByRole('spinbutton',{name:'Valor da cobrança (R$)',exact:true}).fill('8250');await h.capture(mobile,'mobile-create');const bounds=await mobileModal.boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=390);await mobileModal.getByRole('button',{name:'gerar link',exact:true}).click();await mobileModal.getByText('https://mpago.la/review-new',{exact:true}).waitFor();await mobile.close();
 const dark=await h.open(1440,'&theme=dark');await dark.locator('.offers-group').first().waitFor();await h.capture(dark,'dark');await dark.close();
 assert.deepEqual(h.errors,[]);console.log('Links de pagamento: geometria, filtros, cobrança, geração, baixa, estorno, falhas e mobile conferidos.');
} finally {await h.close();}
