import assert from 'node:assert/strict';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('proposals','Propostas',async p=>{await p.getByRole('button',{name:/^Comercial/}).click();await p.getByRole('button',{name:'Propostas',exact:true}).click();});
const measurements=[];
async function measure(page,reference) {return page.evaluate(reference=>{
 const h1=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Propostas'&&e.getClientRects().length),root=reference?h1.parentElement.parentElement.parentElement:document.querySelector('.proposals-page');
 const header=root.children[0],funnel=root.children[1],templates=root.children[2],generated=root.children[3];
 const templateHead=reference?templates.children[1].children[0].children[0]:templates.querySelector('.proposals-table-head'),templateRow=reference?templateHead.nextElementSibling:templates.querySelector('.proposals-template-row');
 const generatedHead=reference?generated.children[1].children[0].children[0]:generated.querySelector('.proposals-table-head'),generatedRow=reference?generatedHead.nextElementSibling:generated.querySelector('.proposals-generated-row');
 const templateCells=Object.fromEntries([...templateRow.children].map((e,i)=>[`templateCell${i}`,e])),generatedCells=Object.fromEntries([...generatedRow.children].map((e,i)=>[`generatedCell${i}`,e]));
 return Object.fromEntries(Object.entries({title:h1,header,funnel,templates,templateIntro:templates.children[0],templateHead,templateRow,generated,generatedIntro:generated.children[0],generatedHead,generatedRow,...templateCells,...generatedCells}).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,height:r.height}];}));
},reference);}
try{
 for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]) {
  const app=await h.open(width),ref=await h.open(width,'',true);await ref.evaluate(async()=>{await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));await Promise.all(document.getAnimations().filter(a=>a.effect?.getComputedTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));});await app.locator('.proposals-template-row').first().waitFor();
  await h.capture(app,`app-${width}`);await h.capture(ref,`reference-${width}`);
  const pair={width,app:await measure(app,false),reference:await measure(ref,true)};measurements.push(pair);
  for(const [name,box] of Object.entries(pair.reference))for(const [k,v] of Object.entries(box))assert.ok(Math.abs(v-pair.app[name][k])<=1,`${width} ${name}.${k}: ${pair.app[name][k]} vs ${v}`);
  await app.close();await ref.close();
 }
 const p=await h.open(1440);await p.locator('.proposals-generated-row').first().waitFor();
 const filters=p.locator('.proposals-filters');
 await p.getByRole('button',{name:'Ver quais',exact:true}).click();assert.equal(await p.locator('.proposals-generated-row').count(),9);
 await filters.getByRole('button',{name:/^Fecharam/}).click();assert.equal(await p.locator('.proposals-generated-row').count(),4);
 await filters.getByRole('button',{name:/^Abertas/}).click();assert.equal(await p.locator('.proposals-generated-row').count(),5);
 await filters.getByRole('button',{name:/^Todas/}).click();assert.equal(await p.locator('.proposals-generated-row').count(),18);
 const row=p.locator('.proposals-generated-row').first();assert.ok((await row.getByRole('link',{name:'abrir ↗',exact:true}).getAttribute('href')).includes('from=cockpit'));
 await row.getByRole('button',{name:'Copiar',exact:true}).click();await row.getByRole('button',{name:'Copiado ✓',exact:true}).waitFor();assert.ok((await p.evaluate(()=>navigator.clipboard.readText())).endsWith('/p/p0'));
 const wa=p.getByRole('link',{name:'Cobrar',exact:true}).first();assert.ok((await wa.getAttribute('href')).startsWith('https://wa.me/'));assert.equal((await wa.getAttribute('href')).includes('from%3Dcockpit'),false);
 const name=p.getByRole('button',{name:/^Editar template:/}).first();const label=await name.getAttribute('aria-label');await name.click();await p.getByRole('textbox',{name:'Nome do template',exact:true}).waitFor();await p.getByRole('button',{name:'Cancelar',exact:true}).click();assert.equal(await p.getByRole('button',{name:label,exact:true}).evaluate(e=>e===document.activeElement),true);
 const duplicate=p.locator('.proposals-template-row').first().getByRole('button',{name:'Duplicar',exact:true});await duplicate.click();const editName=p.getByRole('textbox',{name:'Nome do template',exact:true});assert.ok((await editName.inputValue()).includes('cópia'));
 await editName.fill('Cópia revisada');await p.getByRole('button',{name:'Salvar',exact:true}).click();await p.locator('.proposals-template-row').filter({hasText:'Cópia revisada'}).waitFor();assert.ok(await p.evaluate(()=>window.__reviewMutations.some(m=>m.method==='create'&&m.data.name==='Cópia revisada')));
 const remove=p.locator('.proposals-template-row').filter({hasText:'Cópia revisada'}).getByRole('button',{name:'Excluir',exact:true});p.once('dialog',d=>d.dismiss());await remove.click();assert.equal(await remove.isVisible(),true);p.once('dialog',d=>d.accept());await remove.click();await remove.waitFor({state:'hidden'});
 const create=p.getByRole('button',{name:'Criar template',exact:true});await create.click();await p.getByRole('button',{name:'Salvar',exact:true}).click();await p.getByRole('alert').filter({hasText:'Dê um nome'}).waitFor();await editName.fill('Template de revisão');await p.getByRole('button',{name:'+ adicionar slide',exact:true}).click();await h.capture(p,'editor-desktop');p.once('dialog',d=>d.dismiss());await p.getByRole('button',{name:'Cancelar',exact:true}).click();assert.equal(await editName.inputValue(),'Template de revisão');
 await p.getByRole('button',{name:'Salvar',exact:true}).click();await p.waitForFunction(()=>window.__reviewMutations.some(m=>m.method==='create'&&m.data.name==='Template de revisão'&&m.data.slides.length===3));await p.locator('.proposals-template-row').first().waitFor();await p.close();
 const fail=await h.open(1440,'&failOnce=list');await fail.getByRole('alert').waitFor();assert.equal(await fail.locator('.proposals-funnel').count(),0);await fail.getByRole('button',{name:'Tentar novamente',exact:true}).click();await fail.locator('.proposals-generated-row').first().waitFor();await h.capture(fail,'read-retry');await fail.close();
 const slow=await h.open(1440,'&failOnce=list&holdTemplates');await slow.getByRole('alert').waitFor();await slow.getByRole('button',{name:'Tentar novamente',exact:true}).click();await slow.getByText('Carregando propostas…',{exact:true}).waitFor();await slow.getByRole('button',{name:'Criar template',exact:true}).click();await slow.getByRole('textbox',{name:'Nome do template',exact:true}).waitFor();await slow.close();
 const saveFail=await h.open(1440,'&failOnce=create');await saveFail.getByRole('button',{name:'Criar template',exact:true}).click();await saveFail.getByRole('textbox',{name:'Nome do template',exact:true}).fill('Rascunho preservado');await saveFail.getByRole('button',{name:'Salvar',exact:true}).click();await saveFail.getByRole('alert').filter({hasText:'Falha simulada'}).waitFor();assert.equal(await saveFail.getByRole('textbox',{name:'Nome do template',exact:true}).inputValue(),'Rascunho preservado');await saveFail.getByRole('button',{name:'Salvar',exact:true}).click();await saveFail.locator('.proposals-template-row').filter({hasText:'Rascunho preservado'}).waitFor();await saveFail.close();
 const removeFail=await h.open(1440,'&failOnce=remove');removeFail.once('dialog',d=>d.accept());await removeFail.getByRole('button',{name:'Excluir',exact:true}).first().click();await removeFail.getByRole('alert').waitFor();assert.equal(await removeFail.locator('.proposals-template-row').count(),4);assert.equal(await removeFail.getByRole('button',{name:'Excluir',exact:true}).first().isEnabled(),true);await removeFail.close();
 const previewFail=await h.open(1440,'&failOnce=proposalPreview');await previewFail.getByRole('button',{name:'Criar template',exact:true}).click();await previewFail.getByRole('alert').waitFor();await previewFail.getByRole('button',{name:'Tentar novamente',exact:true}).click();await previewFail.frameLocator('iframe').getByRole('heading',{name:'Prévia de revisão'}).waitFor();await previewFail.keyboard.press('Escape');await previewFail.keyboard.press('Escape');await previewFail.getByRole('heading',{name:'Propostas',exact:true}).waitFor();await previewFail.close();
 const empty=await h.open(1440,'&state=empty');await empty.getByText('Nenhum template neste SaaS',{exact:true}).waitFor();await empty.getByText('Nenhuma proposta gerada ainda.',{exact:true}).waitFor();await h.capture(empty,'empty');await empty.close();
 const mobile=await h.open(390);await mobile.locator('.proposals-template-row').first().waitFor();assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.ok(await mobile.locator('.proposals-templates .tbl-x').evaluate(e=>e.scrollWidth>e.clientWidth));await h.capture(mobile,'mobile');await mobile.getByRole('button',{name:'Criar template',exact:true}).click();await mobile.getByRole('textbox',{name:'Nome do template',exact:true}).fill('Prévia mobile');assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await h.capture(mobile,'mobile-editor');for(const name of ['Salvar','Cancelar']){const r=await mobile.getByRole('button',{name,exact:true}).boundingBox();assert.ok(r.x>=0&&r.x+r.width<=390,`${name} fora da viewport`);}await mobile.getByRole('button',{name:'Salvar',exact:true}).click();await mobile.locator('.proposals-template-row').filter({hasText:'Prévia mobile'}).waitFor();await mobile.close();
 const dark=await h.open(1440,'&theme=dark');await dark.locator('.proposals-template-row').first().waitFor();await h.capture(dark,'dark');await dark.close();

 await h.write('geometry.json',measurements);assert.deepEqual(h.errors,[]);console.log('Propostas: geometria, ações, editor, falhas, mobile e temas conferidos.');
}finally{await h.close();}
