import assert from 'node:assert/strict';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('quick_replies','Respostas rápidas',async p=>{await p.getByRole('button',{name:/^Suporte/}).click();await p.getByRole('button',{name:'Respostas rápidas',exact:true}).click();});
const editor=p=>p.getByRole('dialog',{name:'Resposta rápida',exact:true});
const newReply=async p=>{await p.getByRole('button',{name:'Criar resposta rápida',exact:true}).click();await editor(p).getByLabel('Título',{exact:true}).fill('Resposta fictícia');await editor(p).getByLabel('Texto',{exact:true}).fill('Olá, {{cliente.primeiro_nome}}!');};
const geometry=[];
async function measure(p,ref){return p.evaluate(ref=>{
 const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Respostas rápidas'&&e.getClientRects().length),head=title.closest('header'),root=head.parentElement;
 const list=ref?root.querySelector('section'):document.querySelector('.qr-layout > section'),variables=ref?root.querySelectorAll('section')[1]:document.querySelector('.qr-variables');
 const elements={title,head,toolbar:list.firstElementChild,list,variables};return Object.fromEntries(Object.entries(elements).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,...(['list','variables'].includes(k)?{}:{height:r.height})}];}));
},ref);}
try{
 for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){
  const p=await h.open(width),ref=await h.open(width,'',true);await p.locator('.qr-row').first().waitFor();await h.capture(p,`app-${width}`);await h.capture(ref,`reference-${width}`);const pair={width,app:await measure(p,false),reference:await measure(ref,true)};geometry.push(pair);await h.write('geometry.json',geometry);
  for(const [k,box]of Object.entries(pair.reference))for(const [axis,n]of Object.entries(box))assert.ok(Math.abs(pair.app[k][axis]-n)<=1,`${width} ${k}.${axis}: ${pair.app[k][axis]} vs ${n}`);
  await p.locator('.qr-row').first().click();await p.clock.fastForward(500);await editor(p).locator('.qr-preview').getByText(/Boa tarde, Carla/).waitFor();await h.capture(p,`editor-${width}`);await p.close();await ref.close();
 }
 const p=await h.open(1440);await p.getByLabel('Buscar respostas rápidas').fill('/print');assert.equal(await p.locator('.qr-row').count(),1);await p.getByLabel('Buscar respostas rápidas').fill('');await p.getByRole('button',{name:/^Minhas \d/}).click();assert.equal(await p.locator('.qr-row').count(),1);await p.getByRole('button',{name:/^Todas \d/}).click();
 await newReply(p);await p.clock.fastForward(500);await editor(p).locator('.qr-preview').getByText('Olá, Carla!',{exact:true}).waitFor();await editor(p).getByRole('button',{name:'Salvar',exact:true}).click();await editor(p).waitFor({state:'hidden'});await p.locator('.qr-row').filter({hasText:'Resposta fictícia'}).click();await editor(p).getByLabel('Título',{exact:true}).fill('Resposta revisada');await editor(p).getByRole('button',{name:'Salvar',exact:true}).click();await editor(p).waitFor({state:'hidden'});await p.locator('.qr-row').filter({hasText:'Resposta revisada'}).click();p.once('dialog',d=>d.dismiss());await editor(p).getByRole('button',{name:'Apagar',exact:true}).click();assert.equal(await editor(p).count(),1);p.once('dialog',d=>d.accept());await editor(p).getByRole('button',{name:'Apagar',exact:true}).click();await editor(p).waitFor({state:'hidden'});
 await p.locator('.qr-row').first().getByRole('button',{name:'Duplicar',exact:true}).click();await editor(p).getByLabel('Quem vê').waitFor();assert.equal(await editor(p).getByLabel('Quem vê').inputValue(),'personal');await editor(p).getByRole('button',{name:'Cancelar',exact:true}).click();
 await newReply(p);p.once('dialog',d=>d.dismiss());await editor(p).getByRole('button',{name:'Cancelar',exact:true}).click();assert.equal(await editor(p).count(),1);p.once('dialog',d=>d.accept());await editor(p).getByRole('button',{name:'Cancelar',exact:true}).click();await editor(p).waitFor({state:'hidden'});
 await p.getByRole('button',{name:'Copiar {{saudacao}}',exact:true}).click();assert.equal(await p.evaluate(()=>navigator.clipboard.readText()),'{{saudacao}}');await p.getByLabel('Valor de horario_atendimento',{exact:true}).fill('Das 9h às 17h');await p.getByRole('button',{name:'Salvar variáveis',exact:true}).click();await p.getByText('Variáveis salvas',{exact:true}).waitFor();assert.equal(await p.getByLabel('Valor de horario_atendimento',{exact:true}).inputValue(),'Das 9h às 17h');await p.close();
 for(const method of ['quickReplies','quickReplyCreate','quickReplyPreview','supportSettingsSave']){
  const fail=await h.open(1440,`&failOnce=${method}`);
  if(method==='quickReplies'){await fail.getByRole('alert').waitFor();await fail.getByRole('button',{name:'recarregar',exact:true}).click();await fail.locator('.qr-row').first().waitFor();}
  else if(method==='supportSettingsSave'){await fail.getByLabel('Valor de horario_atendimento').fill('Preservar');await fail.getByRole('button',{name:'Salvar variáveis'}).click();await fail.getByRole('alert').waitFor();assert.equal(await fail.getByLabel('Valor de horario_atendimento').inputValue(),'Preservar');await fail.getByRole('button',{name:'Salvar variáveis'}).click();await fail.getByText('Variáveis salvas',{exact:true}).waitFor();}
  else {await newReply(fail);if(method==='quickReplyPreview'){await fail.clock.fastForward(500);await editor(fail).getByRole('button',{name:'Tentar novamente'}).click();await fail.clock.fastForward(500);await editor(fail).locator('.qr-preview').getByText('Olá, Carla!',{exact:true}).waitFor();}else{await editor(fail).getByRole('button',{name:'Salvar',exact:true}).click();await editor(fail).getByRole('alert').waitFor();assert.equal(await editor(fail).getByLabel('Título',{exact:true}).inputValue(),'Resposta fictícia');await editor(fail).getByRole('button',{name:'Salvar',exact:true}).click();await editor(fail).waitFor({state:'hidden'});}}
  await fail.close();
 }
 const slow=await h.open(1440,'&slow=quickReplyCreate');await newReply(slow);await slow.clock.pauseAt(new Date('2026-09-18T18:05:00Z'));await editor(slow).getByRole('button',{name:'Salvar',exact:true}).click();assert.ok(await editor(slow).getByRole('button',{name:'Salvando…',exact:true}).isDisabled());assert.ok(await editor(slow).getByLabel('Título',{exact:true}).isDisabled());assert.ok(await editor(slow).getByRole('button',{name:'Fechar',exact:true}).isDisabled());await slow.keyboard.press('Escape');assert.equal(await editor(slow).count(),1);await slow.clock.fastForward(2100);await editor(slow).waitFor({state:'hidden'});await slow.close();
 const keys=await h.open(1440);await keys.locator('.qr-row').first().focus();await keys.keyboard.press('Space');await editor(keys).waitFor();await editor(keys).getByLabel('Texto',{exact:true}).fill('Teste: ');await editor(keys).getByRole('button',{name:'+ Inserir variável',exact:true}).click();await keys.getByLabel('Buscar variável',{exact:true}).fill('cliente.primeiro_nome');await keys.getByLabel('Buscar variável',{exact:true}).press('Enter');assert.ok((await editor(keys).getByLabel('Texto',{exact:true}).inputValue()).includes('{{cliente.primeiro_nome}}'));await editor(keys).getByRole('button',{name:'Cancelar',exact:true}).focus();keys.once('dialog',d=>d.dismiss());await keys.keyboard.press('Escape');assert.equal(await editor(keys).count(),1);keys.once('dialog',d=>d.accept());await keys.keyboard.press('Escape');await editor(keys).waitFor({state:'hidden'});await keys.close();
 const readonly=await h.open(1440,'&readonly');await readonly.locator('.qr-row').first().click();assert.ok(await editor(readonly).getByLabel('Título',{exact:true}).isDisabled());assert.equal(await editor(readonly).getByRole('button',{name:'Salvar',exact:true}).count(),0);await readonly.close();
 for(const[width,q]of [[390,''],[1440,'&theme=dark'],[1440,'&empty']]){const page=await h.open(width,q);await h.capture(page,`state-${width}-${q||'mobile'}`);if(q.includes('dark'))assert.equal(await page.locator('.qr-row').first().evaluate(e=>getComputedStyle(e).borderBottomColor),'rgb(29, 43, 54)');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(!q.includes('empty')){await newReply(page);await page.clock.fastForward(500);await h.capture(page,`editor-${width}-${q||'mobile'}`);const box=await editor(page).boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width);assert.ok(await editor(page).evaluate(e=>e.scrollWidth<=e.clientWidth+1));}await page.close();}
 assert.deepEqual(h.errors,[]);console.log('Respostas rápidas: lista/filtros, CRUD, duplicação, variáveis, prévia, falhas/retry, espera, permissões, mobile e tema escuro OK.');
}finally{await h.close();}
