import assert from 'node:assert/strict';import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('settings','Configurações',async p=>{await p.getByRole('button',{name:/^Geral/}).click();await p.getByRole('button',{name:'Configurações',exact:true}).click();},{nativeTimers:true});
const tab=(p,name)=>p.getByRole('navigation',{name:'Seções das configurações'}).getByRole('button',{name,exact:true}).click();
const saved=p=>p.getByRole('button',{name:'salvo ✓',exact:true}).first().waitFor();
const measure=(p,ref)=>p.evaluate(ref=>{const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Configurações'&&e.getClientRects().length),head=ref?title.closest('header'):title.closest('.capsule-page-head'),body=ref?head.nextElementSibling:document.querySelector('.set-cols'),nav=ref?body.querySelector('nav'):document.querySelector('.set-nav'),card=ref?body.querySelector('section'):document.querySelector('.settings-funnel section');return Object.fromEntries(Object.entries({title,head,body,nav,card}).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,height:r.height}]}));},ref);
try{const gs=[];for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){const p=await h.open(width),r=await h.open(width,'',true);await h.capture(p,`app-${width}`);await h.capture(r,`reference-${width}`);const g={width,app:await measure(p,false),reference:await measure(r,true)};gs.push(g);await h.write('geometry.json',gs);for(const k of ['title','head','body','nav','card'])for(const d of ['x','y','width']){if(k==='title'&&d==='width')continue;assert.ok(Math.abs(g.app[k][d]-g.reference[k][d])<1,`${width} ${k}.${d}: ${g.app[k][d]} vs ${g.reference[k][d]}`);}await p.close();await r.close();}
const p=await h.open(1440);const name=p.getByRole('textbox',{name:'Nome da etapa 1',exact:true});const orig=await name.inputValue();await name.fill('Primeiro estágio revisado');await p.getByRole('button',{name:'salvar alterações',exact:true}).click();await saved(p);const w=await p.evaluate(()=>window.__settingsWrites);assert.equal(w.length,2);assert.equal(w[0].renames[orig],'Primeiro estágio revisado');assert.ok(w[1].body.lossReasons);await name.fill('Rascunho descartado');await p.getByRole('button',{name:'descartar',exact:true}).click();assert.equal(await name.inputValue(),'Primeiro estágio revisado');for(const t of ['Próximos passos','Scripts','Equipe','Campos','Integrações']){await tab(p,t);await h.capture(p,`tab-${t}`);}await p.getByRole('textbox',{name:'Conta de anúncios Meta',exact:true}).fill('act_999');await p.getByRole('textbox',{name:'Número WhatsApp ID',exact:true}).fill('12345');await p.getByRole('button',{name:'salvar alterações',exact:true}).click();await saved(p);assert.ok(await p.evaluate(()=>window.__settingsWrites.some(w=>w.body?.waPhoneId==='12345')));await tab(p,'Campos');const field=p.getByRole('textbox',{name:'Rótulo Lead / Contato 1',exact:true});await field.fill('Segmento revisado');await p.getByRole('button',{name:'salvar alterações',exact:true}).click();await saved(p);assert.equal(await p.evaluate(()=>window.__settingsWrites.at(-1).body.customFields.leads[0].label),'Segmento revisado');await p.close();
const partial=await h.open(1440,'&failOnce=update');await partial.getByRole('textbox',{name:'Nome da etapa 1',exact:true}).fill('Etapa salva');await partial.getByRole('button',{name:'salvar alterações',exact:true}).click();await partial.getByRole('button',{name:'erro ao salvar',exact:true}).waitFor();await partial.getByRole('alert').filter({hasText:'Falha simulada'}).waitFor();assert.equal(await partial.getByRole('textbox',{name:'Nome da etapa 1',exact:true}).inputValue(),'Etapa salva');await partial.getByRole('button',{name:'erro ao salvar',exact:true}).click();await saved(partial);await partial.close();
const slow=await h.open(1440,'&longSave');await slow.getByRole('button',{name:'salvar alterações',exact:true}).click();assert.ok(await slow.getByRole('textbox',{name:'Nome da etapa 1',exact:true}).isDisabled());await slow.waitForTimeout(5200);assert.ok(await slow.getByRole('button',{name:'salvando…',exact:true}).isDisabled());await saved(slow);assert.equal(await slow.evaluate(()=>window.__settingsWrites.length),2);await slow.close();
const team=await h.open(1440,'&failOnce=listUsers');await tab(team,'Equipe');await team.getByRole('button',{name:'Tentar novamente',exact:true}).click();await team.getByRole('textbox',{name:'Nome de Leonardo',exact:true}).waitFor();await team.getByRole('combobox',{name:'Nível de Leonardo',exact:true}).selectOption('2');await team.waitForFunction(()=>window.__settingsWrites.some(w=>w.body?.compLevel===2));await team.getByRole('button',{name:'+ usuário do time',exact:true}).click();await team.getByPlaceholder('Nome',{exact:true}).fill('Pessoa revisão');await team.getByPlaceholder('Senha (4+)',{exact:true}).fill('senha-ficticia-123');await team.getByRole('button',{name:'criar usuário',exact:true}).click();await team.getByRole('textbox',{name:'Nome de Pessoa revisão',exact:true}).waitFor();team.once('dialog',d=>d.dismiss());await team.getByRole('button',{name:'Remover Pessoa revisão do time',exact:true}).click();assert.equal(await team.evaluate(()=>window.__settingsWrites.filter(w=>w.method==='removeUser').length),0);team.once('dialog',d=>d.accept());await team.getByRole('button',{name:'Remover Pessoa revisão do time',exact:true}).click();await team.getByRole('textbox',{name:'Nome de Pessoa revisão',exact:true}).waitFor({state:'detached'});await team.close();
const google=await h.open(1440,'&failOnce=googleUserStatus');await tab(google,'Integrações');await google.getByRole('button',{name:'Recarregar Google',exact:true}).click();await google.getByText('conectada · revisao@example.test',{exact:true}).waitFor();google.once('dialog',d=>d.accept());await google.getByRole('button',{name:'desconectar',exact:true}).click();await google.getByRole('button',{name:'Conectar minha conta',exact:true}).waitFor();await google.close();
for(const[width,q]of [[390,''],[1024,''],[1440,'&theme=dark']]){const p=await h.open(width,q);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await h.capture(p,`state-${width}-${q||'responsive'}`);if(width===390)for(const t of ['Próximos passos','Scripts','Equipe','Campos','Integrações']){await tab(p,t);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),t);await h.capture(p,`mobile-${t}`);}await p.close();}
const scripts=await h.open(1440);await tab(scripts,'Scripts');await scripts.getByRole('button',{name:'✎ editar',exact:true}).first().click();await scripts.getByRole('textbox',{name:/^Postura ·/}).fill('Postura revisada');await scripts.getByRole('button',{name:'salvar alterações',exact:true}).click();await saved(scripts);assert.equal(await scripts.evaluate(()=>window.__settingsWrites.filter(w=>w.method==='saveFunnel').length),1);assert.equal(await scripts.evaluate(()=>window.__settingsWrites.filter(w=>w.body?.scripts).length),1);await scripts.close();
const rollback=await h.open(1440,'&failOnce=updateUser');await tab(rollback,'Equipe');await rollback.getByRole('combobox',{name:'Nível de Leonardo',exact:true}).selectOption('2');await rollback.getByRole('alert').waitFor();assert.equal(await rollback.getByRole('combobox',{name:'Nível de Leonardo',exact:true}).inputValue(),'1');await rollback.close();
const lite=await h.open(1440,'&lite');await lite.getByText('Minha conta Google',{exact:true}).waitFor();assert.equal(await lite.getByRole('navigation',{name:'Seções das configurações'}).count(),0);await lite.close();
assert.deepEqual(h.errors,[]);console.log('Configurações: geometria, seis seções, salvar todas/erro parcial, espera >5s, descarte local, equipe/criar/excluir, campos, integrações, retry, Google, mobile e escuro OK.');
}finally{await h.close();}
