import assert from 'node:assert/strict';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('support_settings','Configurações de SLA',async p=>{await p.getByRole('button',{name:/^Suporte/}).click();await p.getByRole('button',{name:'Configurações de SLA',exact:true}).click();});
const save=p=>p.getByRole('button',{name:/^(Salvar|Tudo salvo)$/});
const first=p=>p.getByLabel('1ª resposta Urgente em horas',{exact:true});
const geometry=[];
async function measure(p,ref){return p.evaluate(ref=>{
 const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Configurações de SLA'&&e.getClientRects().length),head=title.closest('header'),root=head.parentElement,cols=ref?root.querySelector('.sla-cols'):document.querySelector('.sla-cols'),card=cols.querySelector('section');
 return Object.fromEntries(Object.entries({title,head,cols,card}).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,...(['cols','card'].includes(k)?{}:{height:r.height})}];}));
},ref);}
try{
 for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){const p=await h.open(width),ref=await h.open(width,'',true);await first(p).waitFor();await h.capture(p,`app-${width}`);await h.capture(ref,`reference-${width}`);const pair={width,app:await measure(p,false),reference:await measure(ref,true)};geometry.push(pair);await h.write('geometry.json',geometry);for(const[k,b]of Object.entries(pair.reference))for(const[a,n]of Object.entries(b))assert.ok(Math.abs(pair.app[k][a]-n)<=1,`${width} ${k}.${a}: ${pair.app[k][a]} vs ${n}`);await p.close();await ref.close();}
 const p=await h.open(1440);assert.ok(await save(p).isDisabled());await first(p).fill('1,5');await first(p).blur();assert.equal(await first(p).inputValue(),'1,5');await p.getByLabel('Nova categoria').fill('Revisão fictícia');await p.getByRole('button',{name:'Adicionar',exact:true}).click();await p.getByRole('switch',{name:'Contar só no expediente',exact:true}).click();assert.ok(await p.getByRole('button',{name:/^Início do expediente:/}).isDisabled());await save(p).click();await p.getByText(/Configurações de SLA salvas/).waitFor();const payload=await p.evaluate(()=>window.__supportSaves.at(-1));assert.equal(payload.saas,'leverads');assert.equal(payload.body.policies.urgent.firstResponseMin,90);assert.equal(payload.body.businessHours.enabled,false);assert.ok(payload.body.categories.includes('Revisão fictícia'));assert.ok(await save(p).isDisabled());
 await first(p).fill('9');await first(p).blur();await p.getByRole('alert').filter({hasText:'A resolução não pode vencer antes'}).waitFor();assert.ok(await save(p).isDisabled());await p.getByRole('button',{name:'Descartar',exact:true}).click();await p.waitForFunction(()=>document.querySelector('input[aria-label="1ª resposta Urgente em horas"]').value==='1,5');await p.getByRole('button',{name:'Copiar',exact:true}).click();assert.ok((await p.evaluate(()=>navigator.clipboard.readText())).endsWith('/s/new/leverads'));
 const lucas=p.getByRole('button',{name:'Lucas atende Elo',exact:true});await lucas.click();assert.equal(await lucas.getAttribute('aria-pressed'),'true');await p.getByRole('checkbox',{name:'Lucas é atendente',exact:true}).click();assert.equal(await p.getByRole('checkbox',{name:'Lucas é atendente',exact:true}).getAttribute('aria-checked'),'false');assert.equal(await p.evaluate(()=>window.__agentSaves.length),2);assert.ok(await p.getByRole('button',{name:'Leonardo atende LeverAds',exact:true}).isDisabled());await p.close();
 for(const method of ['supportSettings','supportSettingsSave','supportAgents','supportAgentSave','linearCatalog']){const fail=await h.open(1440,`&failOnce=${method}`);
  if(method==='supportSettings'){await fail.getByRole('alert').waitFor();await fail.getByRole('button',{name:'recarregar',exact:true}).click();await first(fail).waitFor();}
  else if(method==='supportSettingsSave'){await first(fail).fill('2');await first(fail).blur();await save(fail).click();await fail.getByRole('alert').filter({hasText:'Não deu para salvar'}).waitFor();assert.equal(await first(fail).inputValue(),'2');await save(fail).click();await fail.getByText(/Configurações de SLA salvas/).waitFor();}
  else if(method==='supportAgents'){await fail.getByRole('alert').filter({hasText:'Não deu para carregar os atendentes'}).waitFor();await fail.getByRole('button',{name:'Tentar novamente',exact:true}).click();await fail.getByRole('button',{name:'Lucas atende Elo',exact:true}).waitFor();}
  else if(method==='linearCatalog'){await fail.getByRole('alert').filter({hasText:'Não deu para carregar o catálogo do Linear'}).waitFor();await fail.getByRole('button',{name:'Tentar novamente',exact:true}).click();await fail.getByText(/Falta a chave da API do Linear/).waitFor();}
  else{const target=fail.getByRole('button',{name:'Lucas atende Elo',exact:true});await target.click();await fail.getByText(/Não deu pra salvar Lucas/).waitFor();assert.equal(await target.getAttribute('aria-pressed'),'false');await target.click();assert.equal(await target.getAttribute('aria-pressed'),'true');}
  await fail.close();
 }
 for(const method of ['supportSettingsSave','supportAgentSave']){const slow=await h.open(1440,`&slow=${method}`);await first(slow).waitFor();await slow.clock.pauseAt(new Date('2026-09-18T18:05:00Z'));
  if(method==='supportSettingsSave'){await first(slow).fill('2');await first(slow).blur();await save(slow).click();assert.ok(await slow.getByRole('button',{name:'Salvando…',exact:true}).isDisabled());assert.ok(await first(slow).isDisabled());assert.ok(await slow.getByRole('switch',{name:'Contar só no expediente',exact:true}).isDisabled());await slow.clock.fastForward(2100);await slow.getByText(/Configurações de SLA salvas/).waitFor();assert.equal(await slow.evaluate(()=>window.__supportSaves.length),1);}
  else{await slow.getByRole('button',{name:'Lucas atende Elo',exact:true}).click();assert.ok(await slow.getByRole('button',{name:'Tiago atende LeverAds',exact:true}).isDisabled());await slow.clock.fastForward(2100);await slow.getByRole('button',{name:'Lucas atende Elo',exact:true}).waitFor();assert.equal(await slow.evaluate(()=>window.__agentSaves.length),1);}
  await slow.close();
 }
 for(const[width,q]of [[390,''],[1024,''],[1440,'&theme=dark'],[1440,'&empty'],[390,'&linear']]){const page=await h.open(width,q);await first(page).waitFor();await h.capture(page,`state-${width}-${q||'responsive'}`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));if(q.includes('linear')){await page.getByRole('switch',{name:'Espelhar os tickets deste produto no Linear',exact:true}).click();await page.getByRole('button',{name:/^Time do Linear:/}).click();await page.getByRole('option',{name:'SUP · Suporte',exact:true}).click();await page.getByRole('button',{name:/^Projeto do Linear:/}).click();await page.getByRole('option',{name:'Atendimento',exact:true}).click();await h.capture(page,'mobile-linear');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}if(width===390){await page.getByLabel('Texto de abertura do portal').scrollIntoViewIfNeeded();await h.capture(page,'mobile-portal');await page.getByRole('button',{name:'Lucas atende Elo',exact:true}).scrollIntoViewIfNeeded();await h.capture(page,'mobile-agents');}if(q.includes('empty'))await page.getByText('Nenhum atendente disponível.',{exact:true}).waitFor();await page.close();}
 assert.deepEqual(h.errors,[]);console.log('SLA: cards, horas em minutos, validação/descarte, categorias, expediente, portal, atendentes, falhas/retry, espera e responsividade OK.');
}finally{await h.close();}
