import assert from 'node:assert/strict';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('social','Redes sociais',async p=>{await p.getByRole('button',{name:/^Marketing/}).click();await p.getByRole('button',{name:'Redes sociais',exact:true}).click();});
const geometry=[];
const wizard=p=>p.getByRole('dialog',{name:'criar post',exact:true});
async function measure(p,ref){return p.evaluate(ref=>{const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Redes sociais'&&e.getClientRects().length),head=title.closest('header'),root=head.parentElement;const sections=ref?[...root.querySelectorAll('section')]:[];const els={title,head,today:ref?sections[0]:document.querySelector('.social-today'),kpis:ref?sections[1]:document.querySelector('.social-kpis')};return Object.fromEntries(Object.entries(els).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,height:r.height}]}));},ref);}
const prepareVideo=async p=>{await p.getByRole('button',{name:'Criar post',exact:true}).click();await wizard(p).getByRole('button',{name:/^Vídeo upload/}).click();await wizard(p).getByRole('button',{name:'continuar →',exact:true}).click();await wizard(p).locator('input[type=file]').setInputFiles({name:'video-ficticio.mp4',mimeType:'video/mp4',buffer:Buffer.from('mock-video')});await wizard(p).getByRole('button',{name:'continuar →',exact:true}).click();await wizard(p).getByLabel('Legenda',{exact:true}).fill('Publicação fictícia da revisão');};
try{
 for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){const p=await h.open(width),ref=await h.open(width,'',true);await p.locator('.social-posts a').first().waitFor();await h.capture(p,`app-${width}`);await h.capture(ref,`reference-${width}`);const measured={width,app:await measure(p,false),reference:await measure(ref,true)};geometry.push(measured);for(const key of Object.keys(measured.app))for(const dim of ['x','y','width','height']){if(key==='title'&&dim==='width')continue;assert.ok(Math.abs(measured.app[key][dim]-measured.reference[key][dim])<=1, `${width} ${key}.${dim}`);}await h.write('geometry.json',geometry);await p.getByRole('button',{name:/^Comentários/}).click();await p.locator('.social-comment').first().waitFor();await h.capture(p,`comments-${width}`);await ref.getByRole('button',{name:/^Comentários/}).filter({visible:true}).click();await h.capture(ref,`reference-comments-${width}`);await p.close();await ref.close();}
 const p=await h.open(1440);await p.getByRole('button',{name:'Aumentar criativos de hoje'}).click();await p.getByText('4 criativos registrados hoje',{exact:true}).waitFor();await p.getByRole('button',{name:'por data',exact:true}).click();assert.equal(await p.locator('.social-posts a').first().innerText(),'O que a IA muda no anúncio');await p.getByRole('button',{name:/^Comentários/}).click();let comment=p.locator('.social-comment').first();await comment.getByRole('button',{name:'responder',exact:true}).click();await comment.getByRole('textbox').fill('Resposta fictícia');await comment.getByRole('button',{name:'responder',exact:true}).click();assert.equal(await p.evaluate(()=>window.__socialReplies.length),1);await p.getByRole('button',{name:'Respondidos',exact:true}).click();await p.getByText('Resposta fictícia',{exact:true}).waitFor();await p.getByRole('button',{name:'Todos',exact:true}).click();comment=p.locator('.social-comment').filter({hasText:'Nina'});await comment.getByRole('button',{name:'ocultar',exact:true}).click();await comment.getByRole('button',{name:'mostrar de novo',exact:true}).waitFor();await comment.getByRole('button',{name:'mostrar de novo',exact:true}).click();await comment.getByRole('button',{name:'resolver sem responder',exact:true}).click();await comment.getByRole('button',{name:'reabrir',exact:true}).waitFor();await p.close();
 const fail=await h.open(1440,'&failOnce=socialSummary');await fail.getByRole('alert').waitFor();await fail.getByRole('button',{name:'Tentar novamente',exact:true}).click();await fail.locator('.social-kpis').waitFor();await fail.evaluate(()=>window.__socialFailures={socialComments:1});await fail.getByRole('button',{name:/^Comentários/}).click();await fail.getByRole('alert').waitFor();await fail.getByRole('button',{name:'Tentar novamente',exact:true}).click();await fail.locator('.social-comment').first().waitFor();await fail.evaluate(()=>window.__socialFailures={socialCommentReply:1});const c=fail.locator('.social-comment').first();await c.getByRole('button',{name:'responder',exact:true}).click();await c.getByRole('textbox').fill('Preservar resposta');await c.getByRole('button',{name:'responder',exact:true}).click();await c.getByRole('alert').waitFor();assert.equal(await c.getByRole('textbox').inputValue(),'Preservar resposta');await c.getByRole('button',{name:'responder',exact:true}).click();await fail.close();
 for(const q of ['', '&partial','&failOnce=socialPublish','&slow=socialPublish']){const page=await h.open(1440,q);await prepareVideo(page);if(q.includes('partial'))await wizard(page).getByLabel('Página do Facebook',{exact:true}).check();if(q.includes('slow'))await page.clock.pauseAt(new Date('2026-09-18T18:05:00Z'));await wizard(page).getByRole('button',{name:'publicar agora',exact:true}).click();if(q.includes('slow')){await wizard(page).getByText('⏳ publicando na Meta…',{exact:true}).waitFor();assert.ok(await wizard(page).getByRole('button',{name:'Fechar criação de post',exact:true}).isDisabled());await page.keyboard.press('Escape');assert.equal(await wizard(page).count(),1);await page.clock.fastForward(2100);}if(q.includes('failOnce')){await wizard(page).getByText('Falha simulada na prévia',{exact:true}).waitFor();assert.equal(await wizard(page).getByLabel('Legenda',{exact:true}).inputValue(),'Publicação fictícia da revisão');await wizard(page).getByRole('button',{name:'publicar agora',exact:true}).click();}if(q.includes('partial')){await wizard(page).getByRole('status').waitFor();assert.equal(await wizard(page).getByRole('button',{name:'publicar agora',exact:true}).count(),0);}else await wizard(page).getByText('publicado ✓',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.__socialPublishes.length),1);await page.close();}
 const discard=await h.open(1440);await prepareVideo(discard);discard.once('dialog',d=>d.dismiss());await wizard(discard).getByRole('button',{name:'Fechar criação de post',exact:true}).click();assert.equal(await wizard(discard).getByLabel('Legenda',{exact:true}).inputValue(),'Publicação fictícia da revisão');discard.once('dialog',d=>d.accept());await wizard(discard).getByRole('button',{name:'Fechar criação de post',exact:true}).click();await wizard(discard).waitFor({state:'hidden'});await discard.close();
 for(const[width,q]of [[390,''],[1024,''],[1440,'&theme=dark'],[1440,'&empty'],[1440,'&disconnected']]){const page=await h.open(width,q);await h.capture(page,`state-${width}-${q||'responsive'}`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.getByRole('button',{name:/^Comentários/}).click();await h.capture(page,`comments-${width}-${q||'responsive'}`);await page.getByRole('button',{name:'Criar post',exact:true}).click();await h.capture(page,`wizard-${width}-${q||'responsive'}`);const box=await wizard(page).boundingBox();assert.ok(box.x>=0&&box.x+box.width<=width);await page.close();}
 assert.deepEqual(h.errors,[]);console.log('Redes sociais: painel, métricas, comentários e publicação mock, falhas/retry, parcial, espera, mobile e escuro OK.');
}finally{await h.close();}
