import assert from 'node:assert/strict';
import {reviewHarness} from './harness.mjs';
const h=await reviewHarness('tasks','Tarefas',async p=>{if(!await p.getByRole('button',{name:/^Tarefas/}).isVisible())await p.getByRole('button',{name:/^Geral/}).click();await p.getByRole('button',{name:/^Tarefas/}).click();},{nativeTimers:true});
const geometry=[];
const ready=async p=>{await p.locator('[data-task="t1"]').waitFor();};
const card=(p,id)=>p.locator(`[data-task="${id}"]`);
const measure=(p,ref)=>p.evaluate(ref=>{const title=[...document.querySelectorAll('h1')].find(e=>e.textContent==='Tarefas'&&e.getClientRects().length);const head=ref?title.closest('header'):document.querySelector('.tasks-head');const toolbar=ref?head.nextElementSibling:document.querySelector('.tasks-toolbar');const fields=ref?toolbar.nextElementSibling:document.querySelector('.tasks-card-fields');return Object.fromEntries(Object.entries({title,head,toolbar,fields}).map(([k,e])=>{const r=e.getBoundingClientRect();return[k,{x:r.x,y:r.y,width:r.width,height:r.height}]}));},ref);
try{
for(const width of process.env.REVIEW_FLOWS?[]:[1440,1920]){const p=await h.open(width),ref=await h.open(width,'',true);await ready(p);await h.capture(p,`app-${width}`);await h.capture(ref,`reference-${width}`);const row={width,app:await measure(p,false),reference:await measure(ref,true)};geometry.push(row);for(const key of ['title','head','toolbar','fields'])for(const d of ['x','y','width','height']){if(key==='title'&&d==='width')continue;assert.ok(Math.abs(row.app[key][d]-row.reference[key][d])<=1,`${width} ${key}.${d}: ${row.app[key][d]} / ${row.reference[key][d]}`);}await h.write('geometry.json',geometry);await p.close();await ref.close();}
const p=await h.open(1440);await ready(p);assert.equal(await card(p,'foreign').count(),0);
await p.getByRole('button',{name:'P0',exact:true}).click();assert.equal(await p.locator('.tk-card').count(),1);await p.getByRole('button',{name:'P0',exact:true}).click();
await p.getByRole('textbox',{name:'Buscar tarefas',exact:true}).fill('vídeo');assert.equal(await p.locator('.tk-card').count(),1);await p.getByRole('button',{name:'Limpar busca',exact:true}).click();
await p.getByRole('group',{name:'Campos no card'}).getByRole('button',{name:'Labels',exact:true}).click();assert.equal(await card(p,'t1').getByText('comercial',{exact:true}).count(),0);
await p.getByRole('button',{name:'Recolher A fazer',exact:true}).click();await p.getByRole('button',{name:'Expandir A fazer',exact:true}).click();
await p.getByRole('button',{name:'+ Criar tarefa',exact:true}).click();const input=p.getByRole('textbox',{name:'Nome da tarefa',exact:true});await input.fill('Tarefa de revisão');await input.press('Enter');await p.getByRole('button',{name:'Tarefa de revisão',exact:true}).waitFor();await input.press('Escape');assert.equal(await p.evaluate(()=>window.__taskWrites.filter(w=>w.method==='create').length),1);
await card(p,'t1').focus();await p.keyboard.press('Enter');const panel=p.locator('[data-panel-root]');await panel.waitFor();await panel.getByRole('textbox',{name:'Nome da tarefa',exact:true}).fill('Roteiro revisado');await panel.getByRole('textbox',{name:'Descrição',exact:true}).fill('Descrição revisada');await panel.getByRole('button',{name:'Fechar (Esc)',exact:true}).click();await panel.waitFor({state:'hidden'});assert.equal(await p.evaluate(()=>window.__taskWrites.filter(w=>w.method==='update').length),2);await card(p,'t1').getByRole('button',{name:'Marcar como concluída',exact:true}).focus();await p.keyboard.press('Enter');await p.getByText('Tarefa concluída',{exact:true}).waitFor();assert.equal(await panel.count(),0);await p.locator('.tasks-undo').click();await p.getByText('Tarefa reaberta',{exact:true}).waitFor();
for(const view of ['Lista','Calendário','Cronograma','Quadro']){await p.getByRole('group',{name:'Visualização'}).getByRole('button',{name:view,exact:true}).click();await h.capture(p,`view-${view}`);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
await card(p,'t2').click({modifiers:['Meta']});await card(p,'t3').click({modifiers:['Meta']});const bulk=p.getByRole('toolbar',{name:'Ações da seleção'});await bulk.getByRole('button',{name:'Prioridade',exact:true}).click();await p.getByRole('menuitem',{name:'P0',exact:true}).click();await bulk.waitFor({state:'hidden'});assert.equal(await p.evaluate(()=>window.__taskWrites.filter(w=>w.method==='bulk').length),1);await p.close();
const fail=await h.open(1440,'&failOnce=list');await fail.getByRole('alert').waitFor();assert.equal(await fail.getByText('Nenhuma tarefa ainda',{exact:true}).count(),0);await fail.getByRole('button',{name:'recarregar',exact:true}).click();await ready(fail);await fail.close();
const draft=await h.open(1440,'&failOnce=update');await ready(draft);await card(draft,'t1').click();await draft.getByRole('textbox',{name:'Nome da tarefa',exact:true}).fill('Manter rascunho');await draft.getByRole('button',{name:'Fechar (Esc)',exact:true}).click();await draft.getByRole('button',{name:'não salvou · tentar de novo',exact:true}).waitFor();assert.equal(await draft.getByRole('textbox',{name:'Nome da tarefa',exact:true}).inputValue(),'Manter rascunho');await draft.getByRole('button',{name:'não salvou · tentar de novo',exact:true}).click();await draft.getByRole('button',{name:'Fechar (Esc)',exact:true}).click();await draft.locator('[data-panel-root]').waitFor({state:'hidden'});await draft.close();
const slow=await h.open(1440,'&slow=create');await ready(slow);await slow.getByRole('button',{name:'+ Criar tarefa',exact:true}).click();const creating=slow.getByRole('textbox',{name:'Nome da tarefa',exact:true});await creating.fill('Criação única');await creating.press('Enter');await creating.press('Enter');assert.equal(await creating.getAttribute('readonly'),'');await slow.getByRole('button',{name:'Criação única',exact:true}).waitFor();await slow.waitForFunction(()=>window.__taskWrites.length===1);await slow.close();
const saving=await h.open(1440,'&slow=update');await ready(saving);await card(saving,'t1').click();const title=saving.getByRole('textbox',{name:'Nome da tarefa',exact:true});await title.fill('Primeiro rascunho');await title.press('Tab');await title.fill('Versão mais recente');await saving.getByRole('button',{name:'Fechar (Esc)',exact:true}).click();await saving.locator('[data-panel-root]').waitFor({state:'hidden'});assert.deepEqual(await saving.evaluate(()=>window.__taskWrites.filter(w=>w.method==='update').map(w=>w.body.title)),['Primeiro rascunho','Versão mais recente']);await card(saving,'t1').click();assert.equal(await saving.getByRole('textbox',{name:'Nome da tarefa',exact:true}).inputValue(),'Versão mais recente');await saving.close();
for(const[view,label]of [['Lista','Nova tarefa na lista'],['Calendário','Nova tarefa no calendário']]){const page=await h.open(1440,'&slow=create');await ready(page);await page.getByRole('group',{name:'Visualização'}).getByRole('button',{name:view,exact:true}).click();if(view==='Lista')await page.locator('.tasks-list').getByRole('button',{name:'Adicionar tarefa',exact:true}).first().click();else await page.getByRole('button',{name:'Adicionar tarefa em 2026-09-18',exact:true}).click();const field=page.getByRole('textbox',{name:label,exact:true});await field.fill('Criada '+view);await field.press('Enter');await field.press('Tab');await page.waitForFunction(()=>window.__taskWrites.some(w=>w.method==='create'));assert.equal(await page.evaluate(()=>window.__taskWrites.filter(w=>w.method==='create').length),1);if(view==='Calendário')assert.equal(await page.evaluate(()=>window.__taskWrites.find(w=>w.method==='create').body.dueDate),'2026-09-18');await page.close();}
for(const[width,q]of [[390,''],[1024,''],[1440,'&theme=dark'],[1440,'&empty']]){const page=await h.open(width,q);if(q.includes('empty'))await page.getByText('Nenhuma tarefa ainda',{exact:true}).waitFor();else await ready(page);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await h.capture(page,`state-${width}-${q||'responsive'}`);if(!q.includes('empty')){await card(page,'t1').click();await page.locator('[data-panel-root]').waitFor();await h.capture(page,`panel-${width}-${q||'responsive'}`);if(width===390){await page.getByRole('button',{name:'Prazo 16 set',exact:true}).click();const due=page.getByRole('dialog',{name:'Prazo',exact:true});await due.waitFor();await due.getByRole('button',{name:'Fechar',exact:true}).click();await page.locator('[data-panel-root]').getByRole('button',{name:'Mais ações',exact:true}).click();await page.getByRole('menu').waitFor();await page.keyboard.press('Escape');}assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.getByRole('button',{name:'Fechar (Esc)',exact:true}).click();for(const view of ['Lista','Calendário','Cronograma']){await page.getByRole('group',{name:'Visualização'}).getByRole('button',{name:view,exact:true}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}}await page.close();}
assert.deepEqual(h.errors,[]);console.log('Tarefas: geometria, filtros, campos, quatro visões, edição e retry, criação única, concluir/desfazer, ações em lote, workspace, mobile e escuro OK.');
}finally{await h.close();}
