import assert from 'node:assert/strict';
import { reviewHarness } from './harness.mjs';
import { proposalSlidesPageHtml } from '../../../api/src/proposals/proposal-slides-page.js';

const h = await reviewHarness('today', 'Minhas atividades', null, {nativeTimers:true});
const proposal = { id:'card-preview', data:{lead:{name:'Bruno Teixeira',company:'Auto Peças Já'},answers:{}}, state:{} };
const catalog={products:{ads_essencial:{name:'Ads Essencial',contas:2,anu:{per:599},sem:{per:699}}}};
const html = proposalSlidesPageHtml(proposal, {editable:true,configOnly:true,catalog});
try {
  for (const width of [1440,1920,390]) {
    const page = await h.open(width,'&card');
    await page.getByRole('textbox',{name:'Buscar na fila'}).fill('Bruno');
    await page.locator('.today-open-script').first().click();
    // Configuração nativa: peças do cockpit (sem iframe, sem select nativo) e
    // os planos com o nome da tela Planos, inclusive pacote além de Essencial/Escala.
    const cfgBox=page.locator('.today-presentation .deck-cfg');
    await cfgBox.getByLabel('Pedidos/mês',{exact:true}).waitFor();
    assert.equal(await page.locator('iframe[title="Configurar apresentação"]').count(),0);
    assert.equal(await cfgBox.locator('select').count(),0);
    const saves=()=>page.evaluate(()=>window.__reviewMutations.filter(m=>m.method==='saveProposalConfig').map(m=>m.cfg));
    const saved=async()=>{await cfgBox.getByText('salvo',{exact:true}).waitFor();return (await saves()).at(-1);};
    await cfgBox.getByRole('button',{name:/^Plano LeverAds: Ads Essencial$/}).click();
    const list=page.getByRole('listbox',{name:'Plano LeverAds'});
    assert.ok(await list.getByText('Lever OEM',{exact:true}).isVisible(),'planos agrupados pela linha');
    assert.ok(await list.getByRole('option',{name:/Ads Essencial \+ OEM/}).isVisible());
    await list.getByRole('option',{name:/Ads Enterprise/}).click();
    let last=await saved();
    assert.equal(last.linha+'_'+last.tier,'ads_enterprise');
    assert.equal(await cfgBox.locator('.deck-cfg-value strong').innerText(),'12× R$ 2.997');
    const present=cfgBox.getByRole('link',{name:'Apresentar ↗',exact:true});
    const presentUrl=new URL(await present.getAttribute('href'),page.url());
    assert.equal(presentUrl.searchParams.has('embed'),false);
    assert.equal(presentUrl.searchParams.get('k'),'review');
    assert.equal(await present.getAttribute('target'),'_blank');
    await cfgBox.getByLabel('Pedidos/mês',{exact:true}).fill('420');
    last=await saved();
    assert.equal(last.pedidos,420);
    await cfgBox.getByLabel('Ticket médio (R$)',{exact:true}).fill('85');
    last=await saved();
    assert.equal(last.ticket,85);
    await cfgBox.getByRole('radio',{name:'Semestral · 6×',exact:true}).click();
    last=await saved();
    assert.equal(last.periodo,'semestral');
    assert.equal(await cfgBox.locator('.deck-cfg-value strong').innerText(),'6× R$ 3.297');
    await cfgBox.getByRole('checkbox',{name:/Lever Price/}).click();
    await cfgBox.getByRole('button',{name:/^Plano Lever Price: Lever Price · Escala$/}).waitFor();
    last=await saved();
    assert.equal(last.price,true);
    assert.equal(await cfgBox.locator('.deck-cfg-value strong').innerText(),'6× R$ 3.644');
    assert.equal(last.nome,'Bruno');
    assert.ok(await cfgBox.evaluate(e=>e.scrollWidth<=e.clientWidth));
    await h.capture(page,`card-config-${width}`);
    await page.locator('.lead-answers-editor > summary').click();
    await page.getByRole('combobox',{name:'Quantas contas?'}).selectOption('3-5');
    await page.locator('.lead-answers-editor > summary').click();
    assert.ok(await page.locator('.lead-answers-list').getByText('3 a 5 contas',{exact:true}).isVisible());
    assert.ok(await page.evaluate(()=>window.__reviewMutations.some(m=>m.patch?.accounts==='3-5')));
    assert.ok(await page.locator('.lead-answers-list').evaluate(e=>[...e.querySelectorAll('dt,dd')].every(n=>n.scrollWidth<=n.clientWidth && n.scrollHeight<=n.clientHeight)));
    assert.ok((await page.locator('.lead-answers-list').innerText()).includes('Também quero criar anúncios mais rápido.'));
    await page.locator('.today-script-body').evaluate(e=>e.scrollTop=0);
    await h.capture(page,`card-top-${width}`);
    const rects=await page.locator('.today-script-columns > section').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y}}));
    if(width>=1440) assert.ok(Math.abs(rects[0].y-rects[1].y)<2 && rects[1].x>rects[0].x);
    assert.equal(await page.locator('.today-script').getByRole('heading',{name:'Roteiro',exact:true}).count(),0);
    assert.equal(await page.locator('.today-step').count(),0);
    const shortcut=await page.locator('.today-script-shortcuts').boundingBox();
    const columns=await page.locator('.today-script-columns').boundingBox();
    const history=await page.locator('.today-script-history').boundingBox();
    assert.ok(shortcut.y+shortcut.height<=columns.y+1);
    assert.ok(Math.abs(shortcut.width-columns.width)<2);
    assert.ok(history.y>=columns.y+columns.height-1);
    await page.locator('.today-script-history textarea').fill('Cliente pediu retorno amanhã.');
    await page.locator('.today-script-history').getByRole('button',{name:'registrar',exact:true}).click();
    await page.locator('.today-lead-history-row').getByText('Cliente pediu retorno amanhã.',{exact:true}).waitFor();
    await h.capture(page,`card-history-${width}`);
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
    await page.getByRole('button',{name:'Fechar atividade',exact:true}).click();
    const future=page.getByRole('region',{name:'Atividades futuras'});
    await h.capture(page,`future-${width}`);
    await future.getByRole('button',{name:/\+\d+ atividades/}).click();
    await future.getByRole('button',{name:/Futuro 7/}).click();
    await page.locator('.today-script-identity').getByRole('button',{name:'Futuro 7',exact:true}).waitFor();
    await page.getByRole('button',{name:'Fechar atividade',exact:true}).click();
    await future.getByRole('button',{name:/Mais adiante/}).click();
    await page.locator('.today-script-identity').getByRole('button',{name:'Mais adiante',exact:true}).waitFor();
    await page.close();
  }
  // Proposta sem deck de slides (OEM, de fora): o card segue no iframe da página.
  const fallback = await h.open(1440,'&card&deckIframe');
  await fallback.route('**/p/card-preview?**', route => route.fulfill({contentType:'text/html',body:html}));
  await fallback.getByRole('textbox',{name:'Buscar na fila'}).fill('Bruno');
  await fallback.locator('.today-open-script').first().click();
  await fallback.frameLocator('iframe[title="Configurar apresentação"]').getByLabel('Pedidos/mês',{exact:true}).waitFor();
  await fallback.close();
  assert.deepEqual(h.errors,[]);
  console.log('Card: configuração nativa com os planos do catálogo, fallback em iframe, respostas, histórico, duas colunas e mobile aprovados.');
} finally { await h.close(); }
